### ISSUE TITLE
How to send/receive messages to external API (Express)

### ISSUE THREAD

**Issue by stanleyseow** [OvidijusParsiunas/deep-chat#10]
I read the docs and example but can't figure out how to send and receive messages to Express server...

I hv an express server listen to http://localhost:5050/ask 
```
app.post("/ask", async (req, res) => {
  const prompt = req.body.prompt;
```

i usually use curl to post the messages to the chatbot, it is listening to the prompt
`curl -X POST http://localhost:5050/ask -H 'Content-Type: application/json' -d '{ "prompt": "What is the weather forecast in Kuala Lumpur ?" }'`

The return messages from express are  

```
return res.status(200).json({
          success: true,
          message: msgs,
        }); 
```

Current setup on Vue3 , i use the additionalBodyProps to send the prompt but I m not sure where to get the questions from the users

```
 <deep-chat
    :introMessage="introMessage"
    :request="{
      url: 'http://localhost:5050/ask',
      method: 'POST',
      headers: { customName: 'customHeaderValue' },
      additionalBodyProps: { prompt: messages },
    }"
  >
  </deep-chat>
```

**Comment by OvidijusParsiunas** [comment]
Hi @stanleyseow, you're on the right track.

### Request message from chat
You don't need to define `additionalBodyProps` to add your messages as they are *automatically* added to the outgoing request body using the [Request message](https://deepchat.dev/docs/connect) JSON format.

Your server will either need to be changed to handle the [Request message](https://deepchat.dev/docs/connect) format or you can use the [requestInterceptor](https://deepchat.dev/docs/interceptors#requestInterceptor) property to augment the request body before it leaves the chat. So based on your example you can simply do the following:
```
:requestInterceptor="(request) => {
    request.body = {prompt: request.body.messages[0].text};
    return request;
}"
```

### Response message from server
The response messages from the server need to use the [Result](https://deepchat.dev/docs/connect#Result) format.
So you can either change your responses in the server to be like this:
```
res.json({result: {text: 'Your response text here'}});
```
Or you can use the [responseInterceptor](https://deepchat.dev/docs/interceptors#responseInterceptor) property:
```
:responseInterceptor="(response) => {
    const responseText = // extract it from the response argument
    return {result: {text: responseText}}
}"
```

To note, I'm not sure if this is added intentionally, but you don't need the `headers: { customName: 'customHeaderValue' },` property unless you want to add custom headers when calling your server.

This repository also has a full example for an express server [here](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/node/express). You can look at exampular code for a custom server [here](https://github.com/OvidijusParsiunas/deep-chat/blob/main/example-servers/node/express/src/services/custom.ts) and you can call its endpoint with the following `:request="{url: 'http://localhost:8080/chat'}"`.

**Comment by OvidijusParsiunas** [comment]
Hi, since there has been no further comments for the past 2 days I will be closing this issue now. If you have another queries/issues/suggestions, feel free to create another issue. Thanks!

**Comment by stanleyseow** [comment]
Sorry for no response, I tested the code you posted but it was still not working .... i did not work on it over the weekend...

**Comment by OvidijusParsiunas** [comment]
I'm sorry to hear that, would you mind sharing the code you are using for Deep Chat to see if I can help?

**Comment by OvidijusParsiunas** [comment]
To anyone reading this thread and using the Deep Chat version that is `1.3.0` or higher, the result object has been replaced with [`Response`](https://deepchat.dev/docs/connect#Response).
