### ISSUE TITLE
Regenerate response with same prompt

### ISSUE THREAD

**Issue by rvangari96** [OvidijusParsiunas/deep-chat#107]
Hi,
I need to regenerate a response with the same prompt used before. Please advise on how to do it.

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/120038028/41eed42f-3003-46ca-9b74-318262e74c2a)

**Comment by OvidijusParsiunas** [comment]
Hi @rvangari96.

There are a couple of ways this can be achieved. Here is sample code for two different ways - this is using React syntax but you can pretty much tailor it to your framework:
- Replacing the text element manually. The [`demo`](https://deepchat.dev/docs/demo#demo) property will need to be replaced with [`request`](https://deepchat.dev/docs/connect#request) to your specific API:
```
<DeepChat
  demo={{response: {html: '<div>Response</div> <button class="regenerate">regenerate</button>'}}}
  htmlClassUtilities={{
    regenerate: {
      events: {
        click: (event) => {
          // insert logic to retrieve a new response
          const newText = 'New Response';
          // find text element and insert there
          const previousSibling = (event.target as HTMLElement).previousElementSibling as HTMLElement;
          previousSibling.textContent = newText;
        },
      },
    },
  }}
/>
```
- Overwriting the AI message using the [`overwrite`](https://deepchat.dev/docs/connect#Response) response property and controlling everything in a websocket based [`handler`](https://deepchat.dev/docs/connect#Handler) function:
```
const ref = React.useRef<DeepChatCore>(null);
let signalsRef: any = null;

return (
  <DeepChat
    ref={ref}
    request={{
      handler: (_, signals) => {
        signalsRef = signals;
        signals.onOpen();
        signals.newUserMessage.listener = () => {
          // insert logic to retrieve a response
          signals.onResponse({html: '<div>Text</div><button class="regenerate">Regenerate</button>'});
        };
      },
      websocket: true,
    }}
    htmlClassUtilities={{
      regenerate: {
        events: {
          click: () => {
            // insert logic to retrieve a new response
            signalsRef?.onResponse({
              html: '<div>Response Text</div><button class="regenerate">Regenerate</button>',
              overwrite: true,
            });
          },
        },
      },
    }}
  />
);
```

Let me know if you have any questions.

Thanks!

**Comment by OvidijusParsiunas** [comment]
Closing this issue since there has been no further communication.
Feel free to comment below for anything related to this issue or create a new one for other topics. Thankyou!
