### ISSUE TITLE
Response interceptor not triggering when using OpenAI tools

### ISSUE THREAD

**Issue by devpulse01** [OvidijusParsiunas/deep-chat#108]
Hey Ovidijus,
I've been trying to implement the response interceptor ( as described on https://deepchat.dev/docs/interceptors#responseInterceptor ).

Everything works well without tools, but when I add a tool, the interceptor doesn't trigger for the OpenAI response anymore.

For example, in my case, the interceptor is triggered for the tool call:

```
{
   "id":"chatcmpl-454564641878945465",
   "object":"chat.completion",
   "created":1706708920,
   "model":"gpt-4-0125-preview",
   "choices":[
      {
         "index":0,
         "message":{
            "role":"assistant",
            "content":null,
            "tool_calls":[
               {
                  "id":"call_123456789",
                  "type":"function",
                  "function":{
                     "name":"get_current_weather",
                     "arguments":"{\"location\":\"New York\",\"unit\":\"metric\"}"
                  }
               }
            ]
         },
         "logprobs":null,
         "finish_reason":"tool_calls"
      }
   ],
   "usage":{
      "prompt_tokens":81,
      "completion_tokens":19,
      "total_tokens":100
   },
   "system_fingerprint":""
}
```

---

Then, I return a result formatted like this:

```
[
   {
      "response":"{\"location\":\"New York\",\"temperature\":\"12.5\"}"
   }
]
```

---

However, I'm not able to retrieve the follow-up reply because the interceptor is not triggered.

```
{
  "id": "chatcmpl-456456456421689489",
  "object": "chat.completion",
  "created": 1706708925,
  "model": "gpt-4-0125-preview",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "The current temperature in New York is 12.5°C."
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 64,
    "completion_tokens": 12,
    "total_tokens": 76
  },
  "system_fingerprint": ""
}
```

Am I missing something, or is this behavior expected?
Thank you for your assistance.
Best

**Comment by OvidijusParsiunas** [comment]
Hi @devpulse01.

I have updated the interceptor code for [OpenAI Assistants](https://deepchat.dev/docs/directConnection/OpenAI#Assistant) and published it to version `9.0.119` of `deep-chat-dev` and `deep-chat-react-dev` packages. Can you let me know if that works for you.

Thanks!

**Comment by OvidijusParsiunas** [comment]
Oh, my bad, I'll see what I can change there.

**Comment by OvidijusParsiunas** [comment]
I've made the change in version `9.0.121`. Let me know if this works for you.

**Comment by OvidijusParsiunas** [comment]
That makes sense, I made this change in `9.0.122`.

**Comment by devpulse01** [comment]
Everything is working perfectly. Thank you so much!

**Comment by OvidijusParsiunas** [comment]
Glad to hear it works! I'll include this code in the next release. Thanks!

**Comment by OvidijusParsiunas** [comment]
This has now been deployed in Deep Chat version `1.4.11`. See the [release notes](https://github.com/OvidijusParsiunas/deep-chat/releases/tag/1.4.11) for more.
