### ISSUE TITLE
deepchat.dev documentation link points to wrong URL

### ISSUE THREAD

**Issue by bruffridge** [OvidijusParsiunas/deep-chat#118]
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/1322063/93252ae7-7b86-4b86-8380-22d6279a7919)

Hugging Face API link points to Azure docs.

**Comment by OvidijusParsiunas** [comment]
Thankyou for letting me know about this @bruffridge!

The documentation and all other places have now been updated!
