### ISSUE TITLE
Text to speech support in Firefox

### ISSUE THREAD

**Issue by falahh6** [OvidijusParsiunas/deep-chat#127]
![Screenshot 2024-02-14 at 4 49 47 PM](https://github.com/OvidijusParsiunas/deep-chat/assets/84218073/653e2af4-cb80-488c-8dd5-bfa8ebed4c27)

This is clear. But Firefox latest versions supports 'Speech Synthesis API' 

![Screenshot 2024-02-14 at 4 52 58 PM](https://github.com/OvidijusParsiunas/deep-chat/assets/84218073/3b50f4f5-7bb4-478b-9656-ead61637b999)

Still I'm unable to see the Text to speech working in the firefox.

**Comment by OvidijusParsiunas** [comment]
Hi @falahh6.

I have tested it out on my Firefox and it appears to work ok. May I ask what version of Firefox you are using, what Operating System do you have, does it work for you on Chrome and what code are you using to configure Deep Chat?

This is my version:
<img width="977" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/18709577/c9305a86-dfc3-446e-aa82-595ca9744946">

**Comment by OvidijusParsiunas** [comment]
Since there has been no further communication I will be closing this issue. However feel free to comment below or create a new issue for anything else. Thanks!
