### ISSUE TITLE
OnResponse format with OpenAI and tool_calls

### ISSUE THREAD

**Issue by devpulse01** [OvidijusParsiunas/deep-chat#130]
Hi Ovidijus!

I have a question regarding the use of the onResponse return value when dealing with a tool_call response from OpenAI.

**Context**:
- Using a proxy
- Custom handler
- Custom onResponse

While I can successfully return various response types such as text and files, as described here https://deepchat.dev/docs/connect#Response, I'm not sure about how to integrate this with a tool_call.

For instance, when dealing with streaming, returning the response like this works perfectly:
`return { 'text': response.choices[0].delta.content };`

For non-streaming responses:
`return { 'text': response.choices[0].message.content };`

However, I'm unsure about handling a tool_call.
Does this imply that in scenarios involving a proxy and a custom handler, I would need to handle the tool_call process on my own?

Thank you!

**Comment by OvidijusParsiunas** [comment]
Hi @devpulse01.

Could you share some of the code you are using? If I understand correctly, you are doing everything through the [request handler](https://deepchat.dev/docs/connect/#Handler) and you are not using the [directConnection](https://deepchat.dev/docs/directConnection/OpenAI) property. If this is correct, then I am a little confused on how the `return { 'text': response.choices[0].delta.content };` comes into this context.

Just want to make sure I fully understand the problem incase I give advice. Thankyou!

**Comment by devpulse01** [comment]
Yes, sure.  I have something like this:

request config:

```
{
   ...
   handler: (body, signals) => Proxy.handleRequest(url, method, headers, body, signals)
}
```

Then the handleRequest method:

```
handleRequest(url, method, headers, body, signals){
            try {
                const response = await utils.call(method, url, headers, body, maxRetry);
                signals.onResponse(response);
            } catch (error) {
                signals.onResponse({ error: 'Error while calling proxy endpoint' });
            }
...
}
```

Then on the onResponse:

```
onResponse = (response: any): any => {
       ....
        if (this.isProxy()){
            if (this.isStream()){
                return { 'text': response.choices[0].delta.content };
            }
            return { 'text': response.choices[0].message.content };
        }
       return response;
 }
```

**Comment by devpulse01** [comment]
I suspected it. Now I have confirmation.
Thank you for the link :)
Best

**Comment by devpulse01** [comment]
Hi Ovidijus,

I'm nearing the completion of the code, but I've run into an issue related to stream handling and tool_call.
Specifically, the problem arises when I try to close the stream in the handler.

Here’s the sequence of actions in my current process:

- For a tool call, I first accumulate all the arguments.
- Then, I execute the tool call and return the results to OpenAI.
- After the execution, I emit an event to close the stream, marking the completion of the process.

The response appears correctly in the chat. However, I'm facing a challenge with the code for the stream handler, which is structured as follows:

```
....
onclose() {
    if (!service.asyncCallInProgress) {
        signals.onClose();
    }
    service.emitter.on('asyncCallTerminate', () => {
        signals.onClose();
        service.asyncCallInProgress = false;
    });
}
```

I emit the _**asyncCallTerminate**_ event after sending the OpenAI response. But, when I call signals.onClose(), I got:

![error](https://github.com/OvidijusParsiunas/deep-chat/assets/149673277/08582945-d9a0-4eba-9f2b-4026d08bfcac)

I apologize for all these questions and truly appreciate any guidance.
Best

**Comment by devpulse01** [comment]
Hey Ovidijus, I finally found a solution for this case. I'm closing the ticket.
Thank you.

**Comment by OvidijusParsiunas** [comment]
Glad you got it resolved @devpulse01. Could you share what the solution was if it was to do with Deep Chat, or was it something unrelated?
