### ISSUE TITLE
Deepchat width not stretching full 100%

### ISSUE THREAD

**Issue by phammer** [OvidijusParsiunas/deep-chat#131]
Hi, great work with deep-chat. 

I am prototyping an app using it and found an issue with the 100% on the DeepChat component which seems to not work correctly in context of a Bootstrap.js container.

Reproduction: https://codepen.io/phammer/pen/jOJRBvP

<img width="1859" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/2461650/075d980f-03a3-4888-a01a-af0136b3cb52">

The screenshot shows that even though DeepChat gets 100% width, it doesn't fill the container.

**Comment by OvidijusParsiunas** [comment]
Hi @phammer! 

Deep Chat styling was constructed to fit as many different parent styling situations as possible, with that we had to let go of certain default css properties to prevent unwanted styling behaviours that devs would have to find and _undo_. The down-side of this is ofcourse when devs want particular css behaviours, they may need to a little more tinkering to get to work. Nevertheless, we settled on the _add more_ styling values for more functionality over _remove/undo styling_ to prevent unwanted existing functionality.

I'm sorry to hear this has caused you issues. Thankyou for sharing a live codepen example and I have come up with a simple solution to your problem:

You can add a `display: block` property to the `style` e.g:
```
style="display: block; border-radius: 10px; width: 100%; height: calc(100vh - 20vh);"
```
Other [`display`](https://developer.mozilla.org/en-US/docs/Web/CSS/display) values will also fill the parent container width.

Let me know if this helps! Thanks!

**Comment by phammer** [comment]
Hi @OvidijusParsiunas , 

thx for the fast response! Well appreciated. Yes, that absolutely helps. Thx for spotting it. I assumed there might be some width calculation going on in the component, but this is perfect. 

Have a great day, and keep up the amazing work!

**Comment by OvidijusParsiunas** [comment]
Thankyou @phammer!
