### ISSUE TITLE
Delayed speech recognition 

### ISSUE THREAD

**Issue by AravindKaay** [OvidijusParsiunas/deep-chat#139]
When I say "hi" it is not taken as input when I say something along with Hi then only it takes the word. For example, If I say "Hi" then nothing displays on the screen so afterward if I say "Hello" then it displays as "Hi Hello". The microphone neglects hi when it is says alone. Then when we give a time gap after we spoke and again to make it active we need to say "Hi" to activate the speech recognition.

**Comment by OvidijusParsiunas** [comment]
Hi @AravindKaay.

I first want to make sure there are no bugs in the system. Can you tell me how are you configuring the [`speechToText`](https://deepchat.dev/docs/speech#speechToText) property and what version of Deep Chat are you using.

Having read your problem description - I am 99.9% sure this is to with the [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) and not Deep Chat itself. By default, we use the native browser's [speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) to facilitate the speech to text functionality - which has been facilitated via the [Speech To Element](https://github.com/OvidijusParsiunas/speech-to-element) library. The performance of the inference can really depend on your microphone quality, how close you are to the microphone, the browser you are using and your bandwidth connection. Hence, I am leaning that this a problem in that area. You can test out the inference performance in the following [website](https://speechtoelement.com/) to see if you have the same result.

The only other way that the inference quality can be potentially improved is by using the [Azure](https://deepchat.dev/docs/speech#AzureOptions) service.

Let me know if you face any other issues with this. Thanks!

**Comment by AravindKaay** [comment]
Thanks for your reply, I have tested the speech input on that website. I get the same kind of response. You are correct the issue is not related to deepChat.

**Comment by OvidijusParsiunas** [comment]
Thanks, I will be closing this issue as the functionality is not handled by Deep Chat.
