### ISSUE TITLE
NEXTJS error

### ISSUE THREAD

**Issue by Mohamed-Abdulla** [OvidijusParsiunas/deep-chat#140]
⨯ node_modules\deep-chat\dist\deepChat.js (192:0) @ eval
 ⨯ ReferenceError: navigator is not defined

**Comment by Mohamed-Abdulla** [comment]
"dependencies": {
    "deep-chat-react": "^1.4.11",
    "next": "14.1.2",
    "react": "^18",
    "react-dom": "^18"
  },
  
  
  ⨯ node_modules\deep-chat\dist\deepChat.js (193:0) @ eval
 ⨯ ReferenceError: window is not defined
 
 
 here is the code man 
 
 import dynamic from "next/dynamic";

export default function Home() {
  const DeepChat = dynamic(() => import("deep-chat-react").then((mod) => mod.DeepChat), {
    ssr: false,
  });
  
  
  appreciate ur help . Thanks

**Comment by OvidijusParsiunas** [comment]
The framework version that you are using works for me, so it is likely something else in your project.

It is interesting that you have to use "use client" to make it work, the _ssr: false_ property should take care of it. Are you perhaps rendering this from the _api_ directory files? Also, if you use "use client", does it then work perfectly?

I recommend checking out our [live example](https://stackblitz.com/edit/deep-chat-nextjs?file=pages%2Findex.tsx) or trying to run our [code example](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/nextjs) to see if they work for you and then comparing the difference in those projects to yours to help identify the cause of the problem.

Let me know if you are able to find anything and if you can provide anything else that is unique about your project.

Thankyou!

**Comment by Mohamed-Abdulla** [comment]
No, i'm using app router. no API dir. 

yes if i use use client, it works perfectly.

i looked ur example, you are using pages directory. perhaps that's different

**Comment by OvidijusParsiunas** [comment]
That's good to know, I'll investigate the use the app router and perhaps create more examples. Thanks!

**Comment by OvidijusParsiunas** [comment]
The documentation has now been updated with [live exampels](https://deepchat.dev/examples/frameworks#next) for [App Router](https://stackblitz.com/edit/deep-chat-nextjs-app?file=app%2Fpage.tsx) and [Pages Router](https://stackblitz.com/edit/deep-chat-nextjs?file=pages%2Findex.tsx) APIs.

The repository has also been updated with a new [App Router](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/nextjs/app-router) project and the previous example has been migrated to the [Pages Router](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/nextjs/pages-router) directory.
