### ISSUE TITLE
Pass the response object to a custom element as prop

### ISSUE THREAD

**Issue by shahbazsyed** [OvidijusParsiunas/deep-chat#142]
Hi,
Thanks for the nice work! 

I am using deep-chat in Vue and have the following situation:
I am connecting to the OpenAI API via `request` and add a custom element (`button`) to the response via the `responseInterceptor`.

Here is my custom button defined as a Web component using `defineCustomElement`. Notice the `modelResponse` prop that I am adding to this custom element.

```
const CustomButton = defineCustomElement({
  props:['modelResponse'],
  setup(props){
  const handleClick = () => {
  console.log(props.modelResponse) // currently undefined
  }
  return {
  handleClick
  }
},
 template: `<button @click="handleClick">Click Me</button>`
})
```

Here is how I add it to the `html` using `responseInterceptor`. Please note the way I am trying to pass the text value to `modelResponse` prop.

```
function responseInterceptor(response){
  return {
   text: response.choices[0].message.content,
   html: '<custom-button :modelResponse="text"></custom-button>'
  }
}
```

My issue now is that this `modelResponse` prop is undefined when I log it to the console and I can't figure out if I am doing it wrong. Any guidance here would be highly appreciated. 

My goal is to eventually use the model response inside an event handler for the click event on my custom button to do some additional processing, for example, opening a modal that displays the response text in a specific style. For this, I would need to pass the response to the event that opens this modal. 

I looked at the examples of events in `htmlClassUtilities` but could not find anything on how to pass/communicate with the response object on events dispatched by custom elements.

Thanks again!

**Comment by OvidijusParsiunas** [comment]
Hi @shahbazsyed.

Can you try to use the following syntax instead:
```
html: '<custom-button modelResponse="text"></custom-button>'
```

The problem is that [custom elements](https://deepchat.dev/docs/messages/HTML#customElements) inside Deep Chat are no longer controlled by the parent framework and use the standard [web component](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements) syntax. Hence they should not be treated like Vue elements.

Let me know if this helps. Thanks!

**Comment by shahbazsyed** [comment]
Hi,
Does not seem to work. I still get `undefined` when I log it. Here is some more code for context.

**Custom component** is  SFC (separate .vue file)
// In ChatView.vue
```
<template>
  <deep-chat :responseInterceptor /> 
</template>

const ButtonComponent = defineCustomElement({
  props:['modelResponse'],
  setup(props, {emit}){
    const handleClick = () => {console.log(props.modelResponse)} // undefined!
  },
  return {handleClick}
 },
 template: `<button @click="handleClick">Click Me</button>`
})

// Register custom element
customElements.define('custom-button', ButtonComponent)

```

The `responseInterceptor` function:

```
function responseInterceptor(response){
  return {
   text: response.choices[0].message.content,
   html: '<custom-button modelResponse="text"></custom-button>'
  }
}
```

**Comment by shahbazsyed** [comment]
I also inspected in the dev tools that when this `<custom-button>` is actually rendered, the `modelResponse` prop is changed to `modelresponse` in the DOM and has the value "text" (i.e. the `text` property that stores the actual result in the `responseInterceptor` is not substituted )

**Comment by OvidijusParsiunas** [comment]
Sorry I missed that you are actually using "text" property name. Based on your last comment, here is a better example:

```
function responseInterceptor(response){
  const textResponse = response.choices[0].message.content;
  return {
   text: textResponse,
   html: `<custom-button modelresponse="${textResponse}"></custom-button>`
  }
}
```

Let me know if this works for you, thanks!

**Comment by shahbazsyed** [comment]
This is also unfortunately rendered as the string "${response}" and not interpolated. 

I figured out another way to get access to the `response` object directly in the event handler of the click event. I created a reactive property in my `ChatView.vue` component using `const modelResponse = ref('')` and then in the `responseInterceptor` function I set this property to the actual response text. Now I can directly access this in the `handleClick()` function in the `ButtonComponent`. 

I am not sure if this is optimal but it works for now. Would like to hear your opinion or if there is a better way to do this. 
PS: I am new to Vue so still figuring out the best practices.

**Comment by OvidijusParsiunas** [comment]
Here is a better way of doing it:

- Define your element as follows:
```
const ButtonComponent = defineCustomElement({
  props: ['modelResponse'],
  methods: {
    handleClick() {
      console.log(this.modelResponse);
    },
  },
  template: `<button @click="handleClick">Click Me</button>`,
});

customElements.define('custom-button', ButtonComponent);
```

The response interceptor should then have this code:
```
responseInterceptor(response) {
  const textResponse = response.choices[0].message.content;
  return {
    text: textResponse,
    html: `<custom-button model-response="${textResponse}"></custom-button>`,
  };
},
```

I have tested it locally and it works for me. Let me know if it works for you.
Thanks!

**Comment by shahbazsyed** [comment]
It still gives me the string "$(textResponse)" in the output

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/4356098/c5c415e0-b0af-43e2-8138-5f7aa59cfa21)

**Comment by OvidijusParsiunas** [comment]
Hi @shahbazsyed.

Here is the full code I used, you will have to tailor it to your setup:

```
<template>
  <deep-chat :demo="true" :responseInterceptor="responseInterceptor" />
</template>

<script>
import 'deep-chat';
import { defineCustomElement } from 'vue';

const ButtonComponent = defineCustomElement({
  props: ['modelResponse'],
  methods: {
    handleClick() {
      console.log(this.modelResponse);
    },
  },
  template: `<button @click="handleClick">Click Me</button>`,
});

customElements.define('custom-button', ButtonComponent);

export default {
  methods: {
    responseInterceptor(response) {
      const textResponse = response.text;
      return {
        text: textResponse,
        html: `<custom-button model-response="${textResponse}"></custom-button>`,
      };
    },
  },
};
</script>
```

**Comment by shahbazsyed** [comment]
Thanks! I realised my mistake. I accidentally used regular single quotes instead of back ticks in the html template that I was returning. This caused the interpolation to fail. 

Thanks for your patience in resolving this issue.
