### ISSUE TITLE
[custom type; custom requestHandler]

### ISSUE THREAD

**Issue by GIOVANNI-75** [OvidijusParsiunas/deep-chat#15]
hello, first of all I would like to tell you that I really like what you have done, it’s great work so thank you very much,
I know there is already a ticket from someone asking the same thing, I'm talking about customizing a request to be able to control the response logic, I tried deep-chat-dev but it doesn't work on React and since I'm not a fan of typescript I wanted to ask first before trying to modify myself, and the other thing I wanted to ask you if there was a way to change the structure or the object typing of the cors messages to send, for the moment it's in mode like this {role:"user",text:"sometext"},{role:"ai", text: "someothertext"} I would have liked to receive them on the server side ai and user in the same object {ai:"text", user:"text} if possible,
and thank you again for your work.

**Comment by OvidijusParsiunas** [comment]
Hey @GIOVANNI-75, thankyou for raising this issue.
For the first question - the `handler` logic that you are referring to is almost ready to go (probably will add it to a new package version tomorrow), in the meanwhile I will update the `deep-chat-react-dev` package to give you access to it right now so you can start using it. I will update this thread when the package has been updated.
In regards to the second question, I don't think I fully understand what you mean. If a user sends a message, you would also want to receive the last AI message in a different format (`{ai:"text", user:"text}`). If I understand this correctly, you should be able to do this using a [`requestInterceptor`](https://deepchat.dev/docs/interceptors#requestInterceptor) and modify the message body just the way you want it. However, if you are using the `handler` function, you should be able to do all outgoing message body modifications there.

**Comment by GIOVANNI-75** [comment]
hey, thanks for your response
no I was talking about outgoing messages, currently I am receiving the body on server side
messages:[
{role:ai,text:text},
{role: user, text: text}
];
and I have to modify the structure of messages[] on the server side, so to simplify the process it would be good that the outgoing message will be directly as I expect, hence my question

**Comment by OvidijusParsiunas** [comment]
The `handler` logic is now available inside the `deep-chat-react-dev` package version `9.0.2`. I have explained how to use it in the following [comment](https://github.com/OvidijusParsiunas/deep-chat/issues/12#issuecomment-1707517060) with an upgrade of not having to add the mock `url` property anymore. Let me know if you have any issues when using it, thanks!

**Comment by GIOVANNI-75** [comment]
I'll check it and let you know

**Comment by OvidijusParsiunas** [comment]
The outgoing message body structure that is sent from Deep Chat that into your server can only be changed in the [`requestInterceptor`](https://deepchat.dev/docs/interceptors#requestInterceptor) or the `handler` functions. I am more than happy to help you configure them if you want to avoid changing the message body on your server. Let me know what works better for you. (If I have perhaps misunderstood your request - please provide more info with examples). Thanks!

**Comment by OvidijusParsiunas** [comment]
Just before I forget, the [comment](https://github.com/OvidijusParsiunas/deep-chat/issues/12#issuecomment-1707517060) that I have referenced is using the old response body, it should be `return { text: responseText };`.

**Comment by OvidijusParsiunas** [comment]
You should be able to do that using `handler`. Let me know if you need help.

**Comment by GIOVANNI-75** [comment]
I think I'll wait for the update, it's better, deep-chat-react-dev 9.0.2 doesn't work, without an arg url it fetch http://localhost:3000 and with a fictitious arg url it fetch http://localhost:3000/mock

**Comment by OvidijusParsiunas** [comment]
That version should not be doing that, could you share the code you are using?

This is the configuration I used:
```
<DeepChat
  request={{
    handler: async () => {
      return {text: 'test response'};
    },
 }}
/>
```

**Comment by GIOVANNI-75** [comment]
same problem,
==>
import { DeepChat } from "deep-chat-react-dev";

..
 <DeepChat
..

request={{
        handler: async () => {
       return {text: 'response'};
        },
       }}
..
/>

<==

fetch =>  http://localhost:3000/

**Comment by OvidijusParsiunas** [comment]
That is very strange. Please see the following [CodeSandbox](https://codesandbox.io/s/deep-chat-react-forked-x96y65?file=/src/App.tsx). When you send a message, no network request should be made.

<img width="810" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/18709577/6b36ec1c-796f-472b-9f3c-26c68d7538ce">

But on your app, the chat makes a request?

**Comment by GIOVANNI-75** [comment]
I found the problem, it's stream prop when it's true it doesn't work, unfortunately my logic renders in event/stream, can we do something about that?

**Comment by OvidijusParsiunas** [comment]
Ohhh, that makes sense. I guess I forgot to mention that `handler` currently doesn't work with streams/websockets.
Given the current Deep Chat architecture, it would need a lot of changes to make it work and I am not sure if it is possible as Deep Chat would also need a way to pass the [`signal`](https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters) parameter etc. I will investigate this tomorrow and let you know what I can do.

**Comment by OvidijusParsiunas** [comment]
May I also ask if the core problem is just editing the outgoing body (which can be achieved with [`requestInterceptor`](https://deepchat.dev/docs/interceptors#requestInterceptor)) or are there other things that Deep Chat doesn't provide which would demand the need for `handler`.

**Comment by GIOVANNI-75** [comment]
ah I see, I'm going to go with the other option then for the moment which consists of modifying the outgoing horn while waiting for a better alternative
but thank you very much, that’s already a lot of what you’re doing.

**Comment by OvidijusParsiunas** [comment]
Quick question, if you would use the handler function for event streams, what library would you use. When I'll be analyzing what changes I can make in the library tomorrow it would be great to test things with something that you would use. If possible, could you provide some example code of how you would set up event streams from the browser? Thankyou!

**Comment by GIOVANNI-75** [comment]
for my logic and I think it's the most common logic for an event/stream flux it's to do something like this
stream={true}
equest={{
handler:async() => {
const result = await fetch('api',{
body:{
...
stream:true
...
},
  headers: {
         'Connection': 'keep-alive',
         'Content-Type': 'application/json',
         'Accept': 'text/event-stream'
       },
});
//something like for(const chunck of result.body){
send(text)
if(done)
break;
}
//function to say that the stream is finished something like StreamEnd()
},
}}
