### ISSUE TITLE
Setting state in React resets to initial state.

### ISSUE THREAD

**Issue by oluvvafemi** [OvidijusParsiunas/deep-chat#154]
Anytime I set state in React, for example in responseInterceptors, I lose the message and the component rerenders.

```javascript
const responseInterceptor = (response) => {
  if (response.done) {
    setSomeValue('')
  }
}
``` 

For some cases, I set a global variable as a workaround. But is there a solution for when you really need to set a state.

**Comment by OvidijusParsiunas** [comment]
Hey @oluvvafemi.

This is a standard React practice as changing the state of a component will automatically re-render all of the elements (including Deep Chat) inside it, and with that re-fresh the message state.
The current best solution at the moment is indeed storing the relevant state such as messages inside external state such as an external variable, browser storage, state library or cache. (The DeepChat [Playground](https://deepchat.dev/playground) uses [localstorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to retain all data during re-renders and persist it through multiple client sessions, code [here](https://github.com/OvidijusParsiunas/deep-chat/blob/39e9608b949b1da596e73356942900b380e0be41/website/src/pages/playground.jsx#L46))

Looking into the future, I am very inclined to create a solution that would allow the storage of state through configuration so that devs would no longer need to worry about integrating solutions for their state. I have to get through a couple of features before I can get to that one, but I am very committed to exploring it.

If you have any further questions regarding this let me know. Thanks!

**Comment by oluvvafemi** [comment]
Thank you @OvidijusParsiunas.

**Comment by GoodestUsername** [comment]
> Hey @oluvvafemi.
> 
> This is a standard React practice as changing the state of a component will automatically re-render all of the elements (including Deep Chat) inside it - as well as its message state. The current best solution at the moment is indeed storing the relevant state such as messages inside external state such as an external variable, browser storage, state library or cache. (The DeepChat [Playground](https://deepchat.dev/playground) uses [localstorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to retain all data during re-renders and persist it through multiple client sessions, code [here](https://github.com/OvidijusParsiunas/deep-chat/blob/39e9608b949b1da596e73356942900b380e0be41/website/src/pages/playground.jsx#L46))
> 
> Looking into the future, I am very inclined to create a solution that would allow the storage of state through configuration so that devs would no longer need to worry about integrating solutions for their state. I have to get through a couple of features before I can get to that one, but I am very committed to exploring it.
> 
> If you have any further questions regarding this let me know. Thanks!

How is it setting the messages in there from the local store? It seems like it's saving it in messages in playgroundConfig, but I don't quite understand how the applyPlaygroundConfig function is applying that to the component. Are you forcing it to make a new one each time?

How would you apply it in a simpler example, where your keeping track of just an array of messages in a useRef for one widget?

**Comment by OvidijusParsiunas** [comment]
<b>THE PROPERTY NAMES IN THE FOLLOWING EXAMPLES WILL CHANGE IN THE FUTURE RELEASES</b>

Hi @GoodestUsername.
DeepChat [Playground](https://deepchat.dev/playground) saves the messages from each individual chat component by renewing the corresponding config's`messages` array on each new message as follows:

```
const {messages} = config;
messages.splice(0, messages.length);
messages.push(...deepChatComponent.getMessages());
```

The code for this can be found [here](https://github.com/OvidijusParsiunas/deep-chat/blob/3decba086808c5411c2838d1210d272ada3ae0ba/website/src/pages/playground/chat/playgroundChatComponent.js#L18).

Before the user leaves the current session, all of the chat configs (which are stored inside one `playgroundConfig` object) will be saved to local storage as follows:
```
localStorage.setItem('deep-chat-config', JSON.stringify(playgroundConfig));
```
Code for this is located [here](https://github.com/OvidijusParsiunas/deep-chat/blob/39e9608b949b1da596e73356942900b380e0be41/website/src/pages/playground.jsx#L83).

Finally, relating back to your question about the [`applyPlaygroundConfig`](https://github.com/OvidijusParsiunas/deep-chat/blob/3decba086808c5411c2838d1210d272ada3ae0ba/website/src/pages/playground.jsx#L178) function. It iterates the config which is retrieved from `localStorage` and if you dig down in the function calls eventually passes the messages property into Deep Chat's [`initialMessages`](https://deepchat.dev/docs/messages/#initialMessages) property:
```
initialMessages={config.messages}
```
Code [here](https://github.com/OvidijusParsiunas/deep-chat/blob/3decba086808c5411c2838d1210d272ada3ae0ba/website/src/pages/playground/chat/playgroundChatComponent.js#L81)

If you want a simple example on how to prevent history from disappearing when state is changed in React, then you can simply use a `const` variable outside of the component:

```
import { MessageContent } from "deep-chat/dist/types/messages";
import { DeepChat } from "deep-chat-react";
import { useState } from "react";

const messages: MessageContent[] = [];

export default function App() {
  const [count, setCount] = useState(0);
  
  return (
    <div>
      <DeepChat
        demo={true}
        initialMessages={messages}
        onNewMessage={({message, isInitial}) => {
          if (!isInitial) messages.push(message);
        }}>
      </DeepChat>
      <button onClick={() => setCount((prev) => prev + 1)}>Change State</button>
      {count}
    </div>
  );
}
```

This is also documented for [Vue](https://vuejs.org/) in the following [issue](https://github.com/OvidijusParsiunas/deep-chat/issues/122).

**Comment by GoodestUsername** [comment]
> THE PROPERTY NAMES IN THE FOLLOWING EXAMPLES WILL CHANGE IN THE FUTURE RELEASES
> 
> Hi @GoodestUsername.
> 
> DeepChat [Playground](https://deepchat.dev/playground) saves the messages from each individual chat component by renewing the corresponding config's`messages` array on each new message as follows:
> 
> ```
> const {messages} = config;
> messages.splice(0, messages.length);
> messages.push(...deepChatComponent.getMessages());
> ```
> 
> The code for this can be found [here](https://github.com/OvidijusParsiunas/deep-chat/blob/3decba086808c5411c2838d1210d272ada3ae0ba/website/src/pages/playground/chat/playgroundChatComponent.js#L18).
> 
> Before the user leaves the current session, all of the chat configs (which are stored inside one `playgroundConfig` object) will be saved to local storage as follows:
> 
> ```
> localStorage.setItem('deep-chat-config', JSON.stringify(playgroundConfig));
> ```
> 
> Code for this is located [here](https://github.com/OvidijusParsiunas/deep-chat/blob/39e9608b949b1da596e73356942900b380e0be41/website/src/pages/playground.jsx#L83).
> 
> Finally, relating back to your question about the [`applyPlaygroundConfig`](https://github.com/OvidijusParsiunas/deep-chat/blob/3decba086808c5411c2838d1210d272ada3ae0ba/website/src/pages/playground.jsx#L178) function. It iterates the config which is retrieved from `localStorage` and if you dig down in the function calls eventually passes the messages property into Deep Chat's [`initialMessages`](https://deepchat.dev/docs/messages/#initialMessages) property:
> 
> ```
> initialMessages={config.messages}
> ```
> 
> Code [here](https://github.com/OvidijusParsiunas/deep-chat/blob/3decba086808c5411c2838d1210d272ada3ae0ba/website/src/pages/playground/chat/playgroundChatComponent.js#L81)
> 
> If you want a simple example on how to prevent history from disappearing when state is changed in React, then you can simply use a `const` variable outside of the component:
> 
> ```
> import { MessageContent } from "deep-chat/dist/types/messages";
> import { DeepChat } from "deep-chat-react";
> import { useState } from "react";
> 
> const messages: MessageContent[] = [];
> 
> export default function App() {
>   const [count, setCount] = useState(0);
>   
>   return (
>     <div>
>       <DeepChat
>         demo={true}
>         initialMessages={messages}
>         onNewMessage={({message, isInitial}) => {
>           if (!isInitial) messages.push(message);
>         }}>
>       </DeepChat>
>       <button onClick={() => setCount((prev) => prev + 1)}>Change State</button>
>       {count}
>     </div>
>   );
> }
> ```
> 
> This is also documented for [Vue](https://vuejs.org/) in the following [issue](https://github.com/OvidijusParsiunas/deep-chat/issues/122).

Thanks!
