### ISSUE TITLE
DisplayLoadingBubble is not working for a given time interval

### ISSUE THREAD

**Issue by MOHD-KAIF-hub** [OvidijusParsiunas/deep-chat#156]
Hi, I am utilizing deep-chat but when I am applying api call inside the useEffect getting DisplayLoadingBubble for a few milliseconds
I am trying to show it until the API call is completed it should show can you please review my code I have been working on it last 2 days but didn't get any reliable solution.
and I tried to use a mock API that is giving response after 3 seconds in this case also DisplayLoadingBubble is visible as same.
here is my code please once tell me the mistake Thank you!

// import {DeepChat as DeepChatCore} from 'deep-chat'; <- type
import { DeepChat } from 'deep-chat-react';
import React, { useState, useEffect, useRef } from 'react';
import './style.css';

export const App = () => {
  const chatElementRef = useRef(null);
  const [isLoading,setIsLoading]=useState(false);
 
  const [initialMessages, setinitialMessages] = useState();
  useEffect(() => {
    if (chatElementRef.current) {
      // Set initial messages first
      setinitialMessages([
        { text: 'How are you doing?', role: 'loading' },
        {
          html: `
            <div class="deep-chat-temporary-message">
              <button class="deep-chat-button deep-chat-suggestion-button" style="margin-top: 5px">give some bullet points?</button>
              <button class="deep-chat-button deep-chat-suggestion-button" style="margin-top: 6px">summarize it?</button>
              <button class="deep-chat-button deep-chat-suggestion-button" style="margin-top: 6px">What is this?</button>
            </div>`,
          role: 'user',
        },
      ])
      // Then set the request handler
      chatElementRef.current.request = {
        handler: async(body, signals) => {
          // setIsLoading(true);
          const bodyelement=document.getElementById('messages');
          if(bodyelement)
          console.log(bodyelement);
          const chatbotId = '278efc0a-a1de-42a0-aa7d-ed06dc9f44f8';
          const userQuery = body.messages[0].text;
            setinitialMessages((prev) => ([...prev, { text: userQuery, role: 'user' }]));

   
          try {
            // Make POST request with requestBody
            await fetch('http://34.224.93.99:5000/query-chatbot/', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' }, // Set headers for POST
              body: JSON.stringify({
                chatbotId,
                userQuery,
                source: 'Widget or Iframe',
              })
            })
              .then((response) => response.json())
              .then((data) => {
                // Process response data
                signals.onResponse({ text: data.response });
                setinitialMessages((prev) => ([...prev, { text: data.response, role: 'ai' }]));
              })
              .catch((error) => {
                // Use error.message for better logging
                signals.onResponse({ error: error.message });
                setinitialMessages((prev) => ([...prev, { text: error.message, role: 'error' }]));
                
              });
          } catch (e) {
            signals.onResponse({ error: e.message }); // Use e.message for error logging
            setinitialMessages((prev) => ([...prev, { text: e.message, role: 'error' }]));
          }finally{
               setIsLoading(false);
          }
        }
      };
    }

  }, [chatElementRef]);
  // demo/style/textInput are examples of passing an object directly into a property
  // initialMessages is an example of passing a state object into a property
  return (
    <div className="App">
      <h1>Deep Chat</h1>
      <DeepChat
             
             displayLoadingBubble={isLoading?false:true}

                style={{ width: '100%', height: '460px', border: 'none' }}
                textInput={{
                  styles: {
                    text: { color: 'black' },
                    container: { minWidth: '96%', minHeight: '35px', backgroundColor: '#f5f9ff', borderRadius: '20px', paddingTop: '8px', marginBottom: '2px' },
                    focus: { border: '1px solid #3f6212' }
                  },
                  placeholder: { text: 'Insert text here...', style: { color: '#4459a4' } },
                }}
                submitButtonStyles={{
                  submit: {
                    container: {
                      default: {
                        marginTop: "8px",
                        marginRight: "8px",
                      }
                    },
                    svg: {
                      styles: {
                        default: {
                          width: "25px", // Adjust the width as needed
                          height: "25px", // Adjust the height as needed
                          color: '#3f6212',
                          transform: "rotate(45deg)"
                        }
                      }
                    }
                  }
                }}
                messageStyles={{
                  loading: {
      bubble: {
        backgroundColor: '#475cc7',
        color: 'white',
        fontSize: '16px'
      }
    },
    default: {
      ai: {
        bubble: {
          maxWidth: "350px" // Set max-width for AI messages
        }
      },
      user: {
        bubble: {
          backgroundColor: "lightblue",
          maxWidth: "350px" // Set max-width for user messages
        }
      }
    }
  }}

                initialMessages={initialMessages}

                ref={chatElementRef}
              />
    </div>
  );
};

**Comment by MOHD-KAIF-hub** [comment]
First of all thanks for your response. I got what the mistake I was doing now I will handle thanks a lot.

**Comment by OvidijusParsiunas** [comment]
Hey, I will be closing this issue since the problem has been resolved. Thanks!
