### ISSUE TITLE
Assistants Streaming File Download Links Bug

### ISSUE THREAD

**Issue by jackitaliano** [OvidijusParsiunas/deep-chat#157]
# Scenario
- `deep-chat-dev` `v9.0.156`
- `directConnection` to OpenAI Assistants
- assistant `code_interpretor` tool enabled
- Ask for download link to x file (example: csv, image, etc.), returns sandbox link

# Recreate
- Ask assistant to generate example csv data, and give a download link to file
- Check download link returned
  - with streaming enabled (`deepChatRef.connect.stream = true`): gives sandbox link
  - without streaming enabled: gives data src link
- Refreshing with chat `deepChatRef.directConnection.openAI.assistant.load_thread_history = true` gives correct data src link

# Reference
[Direct Connection Fails to Stream Response: OpenAI Assistance | Issue #155](https://github.com/OvidijusParsiunas/deep-chat/issues/155)

I'm aware this functionality was just added, and only to dev so far, so not expecting immediate fix. Just wanted to bring the bug to your attention.

# Screenshots
![sandboxLink](https://github.com/OvidijusParsiunas/deep-chat/assets/93797825/8c47aae1-dbd4-45f2-8152-ed546c6a696b)

*Link with sandbox (link seen in devtools)*

![dataLink](https://github.com/OvidijusParsiunas/deep-chat/assets/93797825/d9bfc12a-9450-4c3d-973b-62b72a0b0826)

*Link with data src link after refresh (link seen in devtools)*

**Comment by OvidijusParsiunas** [comment]
Hi, my sincere apologies for the late reply. I started my new job yesterday and immediately got his with the reality of having less free time. I spent a good bit of time analyzing the problem and it does appear to be on Deep Chat side of things, meaning I can fix it! The problem itself will likely require the ability to post-process a streamed message, which is not very trivial, hence I will need to spend an extended amount of time on fixing this. Please bare with me and I should get it fixed in a couple of days. Thankyou!

**Comment by jackitaliano** [comment]
> Hi, my sincere apologies for the late reply. I started my new job yesterday and immediately got his with the reality of having less free time. I spent a good bit of time analyzing the problem and it does appear to be on Deep Chat side of things, meaning I can fix it! The problem itself will likely require the ability to post-process a streamed message, which is not very trivial, hence I will need to spend an extended amount of time on fixing this. Please bare with me and I should get it fixed in a couple of days. Thankyou!

No worries, good luck with the new job!

**Comment by OvidijusParsiunas** [comment]
Hey @jackitaliano.

I've been busy working on other issues at the moment and will try to get to this as soon as I possibly can. Thankyou!

**Comment by OvidijusParsiunas** [comment]
Hey @OvidijusParsiunas.

This should now be fixed in `deep-chat-dev` and `deep-chat-react-dev` version `9.0.164`. Let me know if this helps!

**Comment by OvidijusParsiunas** [comment]
Hi, the functionality mentioned in this issue has now been released in Deep Chat version `2.0.0`.
