### ISSUE TITLE
Combination of streaming and mixedFiles not working

### ISSUE THREAD

**Issue by ki-zeitalter** [OvidijusParsiunas/deep-chat#160]
Hi there and first of all thank you for this fantastic component.

Currently I'm using version 1.4.11 and I'm trying to use file upload in combination with streaming responses. When I set mixedFiles and stream to true then the back-end is not able to parse the request correctly. I had a closer look at the RequestDetails and I saw that the content type was changed to "text/plain" instead of "multipart/formdata" when streaming is activated.

Am I doing something wrong here or is the combination not working?

**Comment by OvidijusParsiunas** [comment]
Hi @ki-zeitalter.

This was indeed a bug. I have fixed it in `deep-chat-dev` and `deep-chat-react-dev` packages version `9.0.157`. These packages behave the same except their names are different.
To note, we are preparing for a big release soon, and some of the properties are different. Such as `request` being called `connect` and the `stream` property being moved to `connect`. Nevertheless, everything is backwards compatible and you should be able to use the old properties as needed, but you will get console and TS warnings which you can ignore.

Let me know if this works for you.
Thanks!

**Comment by ki-zeitalter** [comment]
Wow that was quick! It works indeed! Thanks alot!

**Comment by OvidijusParsiunas** [comment]
Hi, the functionality mentioned in this issue has now been released in Deep Chat version `2.0.0`.
