### ISSUE TITLE
Return multiple responses with custom API

### ISSUE THREAD

**Issue by littlepenguin89106** [OvidijusParsiunas/deep-chat#162]
I wonder how I handle multiple responses from my custom API?
The `Response` object only contains one `MessageContent` , maybe deep-chat could support array of `MessageContent` ?

**Comment by OvidijusParsiunas** [comment]
Hi @littlepenguin89106.
Please see the following issue where this question was asked:
https://github.com/OvidijusParsiunas/deep-chat/issues/83

Thankyou!

**Comment by littlepenguin89106** [comment]
Thanks, I will try to use websocket for multiple responses
