### ISSUE TITLE
Option to import other react component inside the deepchat  

### ISSUE THREAD

**Issue by anup-singh** [OvidijusParsiunas/deep-chat#171]
Hi,
I was wondering if there is any easy option to import custom react/jquery component inside deep-chat. Like Image gallery/carousel/

example image is mentioned below.
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/6386991/f4cbca72-8bac-4356-a652-bd0ffccb5944)

**Comment by OvidijusParsiunas** [comment]
Hi @anup-singh.

Apologies for the late reply as I have been very busy with my work. The answer to your question is _yes_, as long as it is an actual [custom element](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements).

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue as there has been no further activity.
