### ISSUE TITLE
Display loadingBubble override

### ISSUE THREAD

**Issue by abhinavverma-sf** [OvidijusParsiunas/deep-chat#179]
![Screenshot from 2024-04-24 22-18-27](https://github.com/OvidijusParsiunas/deep-chat/assets/85155309/965e59a8-93d1-4942-955e-fbecb9af6e83)

Hi I went through the docs mentioned. I found how could I write my own styles for message and chat and inputbox, but not for three dots loading bubble.. 

Is it possible by any chance that we can override it?

**Comment by abhinavverma-sf** [comment]
Hi @OvidijusParsiunas any update?

**Comment by buzhou9** [comment]
There is no custom loading effect provided, but I have found this source code. You can clone the code and make modifications to get your own version
```javascript
// src /component/src/views/chat/messages/messages.ts
public addLoadingMessage() {
    if (!this._displayLoadingMessage) return;
    const messageElements = this.createMessageElements('', MessageUtils.AI_ROLE);
    const {outerContainer, bubbleElement} = messageElements;
    bubbleElement.classList.add('loading-message-text');
    const dotsElement = document.createElement('div');
    dotsElement.classList.add('dots-flashing');
    bubbleElement.appendChild(dotsElement);
    this.applyCustomStyles(messageElements, MessageUtils.AI_ROLE, false, this.messageStyles?.loading);
    LoadingMessageDotsStyle.set(bubbleElement, this.messageStyles);
    this.elementRef.appendChild(outerContainer);
    ElementUtils.scrollToBottom(this.elementRef);
  }
```

**Comment by buzhou9** [comment]
This is a branch where I made modifications to the fork source code repository. Thank you to the author, as the structure of the source code is very easy to expand. We can easily add this feature.

https://github.com/buzhou9/deep-chat/tree/feature-customLoadingContent

To modify the style of the outer container, you can refer to the official documentation of the component. Here is the address

https://deepchat.dev/docs/messages/styles/#MessageElementsStyles

```html
<deep-chat
      id="chat-element"
      demo="true"
      textInput='{"placeholder":{"text": "Welcome to the demo!"}}'
      messageStyles='{
        "loading": {
          "innerContainer": { "width": "100%" },
          "bubble": { "background": "none","width":"100%","maxWidth":"100%" },
          "content": "<div style=\"background: #00e0e0;color: #5d5d5d;text-align: center;\">new loading ....</div>"
        }
      }'
    ></deep-chat>
```

UI demonstration

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/26274418/445799e4-4964-4c8b-b9d4-bbd221dce765)

**Comment by OvidijusParsiunas** [comment]
That is a nice demonstration by @buzhou9.

As mentioned, there is no standard way to override the styling of the loading bubble beyond the properties that are provided in the `loading` property of the [`messageStyles`](https://deepchat.dev/docs/messages/styles/#messageStyles) object.

If you want to change the element and its contents as in your example, you will have to fork/clone this repository, set up the project locally (which is very easy to do following these [instructions](https://github.com/OvidijusParsiunas/deep-chat/tree/main/component#construction_worker-to-create-your-own-deep-chat-component)) and make the necessary changes in the following files: [LoadingMessageDotsStyle.ts](https://github.com/OvidijusParsiunas/deep-chat/blob/8c56e3a3d0aac06461b8f4b53bcd64c35dcb231f/component/src/views/chat/messages/loadingMessageDotsStyle.ts#L4) and [loadingIcon.css](https://github.com/OvidijusParsiunas/deep-chat/blob/main/component/src/views/chat/input/buttons/submit/loadingIcon.css).
