### ISSUE TITLE
Handling line breaks while streaming responses

### ISSUE THREAD

**Issue by ronald888** [OvidijusParsiunas/deep-chat#180]
Since streaming data returns chunked text, a newline character can be split between \ and n. What's the best way to handle such a scenario? Is it possible to cache the response through the response interceptor?

**Comment by OvidijusParsiunas** [comment]
Hi @ronald888.

If you want to have new lines in your messages, you can add \n\n in the place where you want to have them.
Let me know if this helps you.

Thanks!

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue as there has been no further activity.

**Comment by OvidijusParsiunas** [comment]
Hi, this has now been improved and new lines will now be rendered by simply having `\n` in your text message. This is now available in our `deep-chat-dev` and `deep-chat-react-dev` packages version `9.0.173` and will be added to the next release of our main package (_after 1.4.11_).
