### ISSUE TITLE
Adding custom elements in input area

### ISSUE THREAD

**Issue by K-Jadeja** [OvidijusParsiunas/deep-chat#181]
Hey @OvidijusParsiunas,
I was wondering if there was a way to add a custom element at the 'outside-left' position of the textbox area, so if we could somehow change the buttons on the default dropdown to execute custom functions
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/113630783/70c9514c-fc54-43fa-854e-50fd86cec340)

My aim is to give an option to toggle chatbot features like 'use web' or 'temporary chat' similar to how bing chat does it
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/113630783/e97b921b-ed8b-4406-a6a4-d030cb136651)

Appreciate any guidance here

**Comment by OvidijusParsiunas** [comment]
Hi @K-Jadeja. Unfortunately right now there is no ability to add custom buttons/elements to the input panel. However I do plan to add such functionality in the future. I will re-open this issue when I begin the work on this. Thankyou!
