### ISSUE TITLE
requestInterceptor: how to wait before sending request

### ISSUE THREAD

**Issue by hauselin** [OvidijusParsiunas/deep-chat#185]
I'm using sveltekit and I'm trying to use `requestInterceptor` to intercept a request. Specifically, I'm trying to wait for some event to happen so some variable changes before I send the request. How can I do that? Thanks! 

```svelte
// +page.svelte

let x = false;
const f = () => {
    // do something so x becomes true
}

requestInterceptor={(details) => {
	
	f(); 
	// how to wait for f() to finish running so x becomes true? if x is false, the request should not be sent

    if (x) {
        return details;
    }

}}
```

**Comment by buzhou9** [comment]
Asynchronous operations can be handled using "async, await"
```javascript
// +page.svelte

let x = false;
const f = async () => {
    // do something so x becomes true
}

requestInterceptor={async (details) => {
	
	await f(); 
	// how to wait for f() to finish running so x becomes true? if x is false, the request should not be sent

    if (x) {
        return details;
    }

}}
```

**Comment by OvidijusParsiunas** [comment]
Great example from @buzhou9! Everything is spot on!

Another way you can _test_ the [`await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) operator is by giving the `f` function the following value (the returned [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) works exactly like @buzhou9's [`async`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)):
```
const f = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      x = true;
      resolve();
    }, 2000);
  });
}
```

**Comment by hauselin** [comment]
Thanks both!
