### ISSUE TITLE
Intercom / Crisp style popup from button embed

### ISSUE THREAD

**Issue by Matt2012** [OvidijusParsiunas/deep-chat#187]
Is there way to embed as an open/close chat button like many chatbots ?
https://react-chatbotify.tjtanjin.com/docs/api/bot_options#chatbutton
(See also bottom right of page for example)

**Comment by OvidijusParsiunas** [comment]
Hi @Matt2012.

This is something that we consider adding in the future but are currently working on other more immediate priorities.

Nevertheless, there is another [issue](https://github.com/OvidijusParsiunas/deep-chat/issues/189) which encourages other community members to try implementing this and we would gladly give a shoutout for their work.

**Comment by OvidijusParsiunas** [comment]
Because this issue is referenced in [another one](https://github.com/OvidijusParsiunas/deep-chat/issues/189), I will close it and any further comments should go in there. Thankyou!
