### ISSUE TITLE
Stream text and html

### ISSUE THREAD

**Issue by m1nka** [OvidijusParsiunas/deep-chat#188]
We want to display a server reponse together with some [custom button](https://deepchat.dev/docs/messages/HTML/). So our goal is to display something like this:

<img width="363" alt="Screenshot 2024-05-08 at 17 34 28" src="https://github.com/OvidijusParsiunas/deep-chat/assets/6085453/660a23a5-9051-4fd5-a7e9-782bf94f0b7a">

We can successfully send either `html` or `text`, but we cannot send both in the same response. This would be extremely helpful since with AI agents we need to give an anwer to the user and then present some options to reply.

If we send a stream back with `text` **and** `html` at the same time like this (server-side code):
```js
for await (const chunk of answerStream) {
        if (chunk.choices[0].delta.content) {
          await stream.write(
            `data: ${JSON.stringify({
              text: `${chunk.choices[0].delta.content}`,
              role: `assistant`,
              html: `<button class="deep-chat-button deep-chat-suggestion-button" style="margin-top: 5px">What do shrimps eat?</button>`
            })}\n\n`
          );
        }
      }
```
the `html` is just ignored. And if we send `text` first (which works fine) and some `html` at the end 
```js 
stream.write(`data: ${JSON.stringify({
        role: `assistant`,
        html: `<button class="deep-chat-button deep-chat-suggestion-button" style="margin-top: 5px">What do shrimps eat?</button>`
      })}\n\n`)
```
we get a Deepchat error: 

> Cannot mix {text: string} and {html: string} responses.

Is this a bug? How can we work around this? We need to provide the user with a `text` answer and custom elements. 

Thanks a lot!

**Comment by buzhou9** [comment]
You can try returning an HTML fragment containing text content and adding styles to it to achieve the desired effect, which only requires the use of HTML attributes.

**Comment by OvidijusParsiunas** [comment]
The response given by @buzhou9 is a great one!

Unfortunately Deep Chat does not allow the server to stream `text` and `html` at the same time as it is a very unnatural use-case and something that is difficult to parse/render for the same message. However, I can see that for your use-case you want to add the `html` message as a separate message, so as an alternative to the @buzhou9 suggestion, you can also try to listen to when the stream has finished and add the suggestion message manually. Details on how to do that are listed in the following [issue](https://github.com/OvidijusParsiunas/deep-chat/issues/174)

Let me know if this helps. Thanks!

**Comment by OvidijusParsiunas** [comment]
Hi, I will be closing this issue since there has been no further communication. Thanks!

**Comment by kuafucode** [comment]
@OvidijusParsiunas while tring to append html after streaming text, I found this github issue. In my case I prefer to have server to stream the response, analyze the response, and attach suggested actions (html buttons) with security keys in the actions urls, all in one backend request. This can be perfectly delivered if we allow mixing text and html (or at least append html as one last stream event).

Can we reopen this issue?

**Comment by OvidijusParsiunas** [comment]
@kuafucode mixing text and html with streams is quite complex and not to mention would require a rewrite of the entire message stream code logic. Additionally most use-cases do not require this and the edge cases that do can usually be achieved in other ways.

So for your use-case you can use the [responseInterceptor](https://deepchat.dev/docs/interceptors#responseInterceptor) to monitor what is being returned from your server, and when you return the `html` message, all you need to do is to add it via the [addMessage](https://deepchat.dev/docs/methods#addMessage) method instead.

Something like this:
```
chatElementRef.responseInterceptor = (response) => {
  if (response.html) {
    chatElementRef.addMessage({html: response.html});
  }
  return {text: ''};
};
```

Ofcourse, what the actual html property name is and how it is indicated will be determined by your own server and the UI.
Thanks!
