### ISSUE TITLE
Scrolling styles in the chat container

### ISSUE THREAD

**Issue by Fileofish** [OvidijusParsiunas/deep-chat#19]
Hello! Thank you so much for working on the component, great job!

Can I clarify how it is possible to change the scrolling styles in the chat container?

Unfortunately, direct access to the component selector in css, using the pseudo-attribute ::-webkit-scrollbar and !important did not bring results.
The use of the scrollbarWidth (scrollbar-width) prop in styles in containerStyle and message Styles also did not bring results.

Thank you in advance for the answer!

**Comment by OvidijusParsiunas** [comment]
Hi @Fileofish, the scrollbar styles should be applied via the [`auxiliaryStyle`](https://deepchat.dev/docs/styles/#auxiliaryStyle) property which accepts a css that contains _webkit_ and other formats of css.

You can use it as:
```
<deep-chat
  auxiliaryStyle="
    ::-webkit-scrollbar {
      width: 10px;
      height: 10px;
    }
    ::-webkit-scrollbar-thumb {
      background-color: #54a7ff;
      border-radius: 5px;
    }"
></deep-chat>
```

This example can ofcourse be changed to work as a property (`chatElementRef.auxiliaryStyle = '...'`) and tailored to your framework of choice.
Please note that webkit css is not standardized across all browsers such as Firefox so it is best to check if what you are using is supported by your browser [here](https://caniuse.com/).

Let me know if this helps, thanks!!

**Comment by Fileofish** [comment]
Thanks for the quick response [OvidijusParsiunas](https://github.com/OvidijusParsiunas)! 

It helped. 😊 😌

Successful projects for you in the future!

**Comment by OvidijusParsiunas** [comment]
Thankyou! I'll close this issue :)
