### ISSUE TITLE
Dynamically add responses for long-running tasks

### ISSUE THREAD

**Issue by nileshtrivedi** [OvidijusParsiunas/deep-chat#192]
There are use-cases where agent can be asked to perform a task which can take time much longer than typical web request timeout limit. For example: "Research and prepare a report", "Confirm with James if this task is ready to be picked up?"

Is there a way for a custom backend to push a message into a visible chat thread? If the user were to reload the page, `initialMessages` could be updated, but this is not ideal. 

Perhaps this can be achieved simply by an automatic periodic refresh of the conversation using `setInterval` ?

**Comment by buzhou9** [comment]
Perhaps this can be done by manually using the "deepChatInstance. addMessage" method after receiving the message to add the content to the current conversation process

**Comment by nileshtrivedi** [comment]
@buzhou9 Yeah, just got to know about `_addMessage`. That might work too.

**Comment by OvidijusParsiunas** [comment]
Hi, the functionality mentioned in this issue is now available in Deep Chat version `2.0.0`.
