### ISSUE TITLE
[Docs]: Docs > Messages > HTML > Bubble Style references broken link to missing 'messageStyles'

### ISSUE THREAD

**Issue by johnemau** [OvidijusParsiunas/deep-chat#197]
[![image](https://github.com/OvidijusParsiunas/deep-chat/assets/309310/e30e6468-13bb-4e73-b58b-9ad9ec9a5762)](https://deepchat.dev/docs/messages/HTML#bubbleStyle)

But [messageStyles](https://deepchat.dev/docs/styles/#messageStyles) does not exist elsewhere in the documentations.

**Comment by johnemau** [comment]
I just found it, the link should just be updated to https://deepchat.dev/docs/messages/styles/#messageStyles

**Comment by OvidijusParsiunas** [comment]
Hi @johnemau.
Thankyou for letting us know about the problem. This has now been fixed.
