### ISSUE TITLE
Microphone recording audio format issue

### ISSUE THREAD

**Issue by delsoul6104** [OvidijusParsiunas/deep-chat#204]
When enabling the microphone function to record, I have set the audioRecordingFiles to:
`audioRecordingFiles: {
    format: "wav",
    maxDurationSeconds: 3600,
}`
However, when uploading to the backend, although the file extension is .wav, the format is still parsed as webm. How can this be resolved? Thank you.

**Comment by delsoul6104** [comment]
When I specify the format as webm, uploading formdata to the backend program developed with .NET Core and saving it locally, the webm format is fine. However, if I set the audio format to mp3 in deep-chat, although the file extension is mp3 when uploaded to the backend, it still parses as webm

**Comment by delsoul6104** [comment]
I found another issue with uploading an AUDIO file,
`:audio="audio"
audio:{
"files": {"acceptedFormats": ".mp3,.wav,.webm"},
"button": {"position": "outside-left"}
}`
, after clicking the button and selecting a wav file, 
upon executing the submit action, an error message appears stating 
"The program cannot access the file because it is being used by another process"
程序無法存取檔案，因為檔案正由另一個程序使用。 (0x80070020) deepChat.js:3265

I only performed the action of selecting and uploading a file

**Comment by OvidijusParsiunas** [comment]
Hmmmmm, I have tested this on my computer and I can upload mp3 files just fine.
When you get this error, can you try to upload the mp3 file to some other website to see if it is not an OS or a browser issue?

**Comment by delsoul6104** [comment]
> Hmmmmm, I have tested this on my computer and I can upload mp3 files just fine. When you get this error, can you try to upload the mp3 file to some other website to see if it is not an OS or a browser issue?

I ran deep-chat locally and uploaded an audio file, but the file is still inaccessible. I also tried uploading the MP3 file to https://www.freeconvert.com/mp3-to-wav for testing, and it was successfully uploaded. My development environment is Windows 11.

**Comment by delsoul6104** [comment]
I still cannot upload. Can disable the preview upload audio file，like this
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/20633031/5304aa63-55c6-41e8-b087-01c0e9f6e93c)

thank u~~~~

**Comment by OvidijusParsiunas** [comment]
Hi @delsoul6104.
I would recommend you to fork/clone the repository and run it locally yourself to see if you can fix the issue. It is actually very easy to do if you follow the setup guide [here](https://deepchat.dev/docs/directConnection/). You can start by editing the following [file](https://github.com/OvidijusParsiunas/deep-chat/blob/2a9b6921ad7d39570ef5f4a8eae3d41d403bd8c9/component/src/views/chat/input/buttons/microphone/recordAudio.ts#L7). Let me know if you need any further help!

**Comment by delsoul6104** [comment]
hi @OvidijusParsiunas , I have deployed the deepchat project to the server and conducted tests for audio file uploads. However, I still encounter the error message "The process cannot access the file because it is being used by another process (0x80070020)." I don't know how to resolve this issue.

**Comment by delsoul6104** [comment]
> Hi @delsoul6104. I would recommend you to fork/clone the repository and run it locally yourself to see if you can fix the issue. It is actually very easy to do if you follow the setup guide [here](https://deepchat.dev/docs/directConnection/). You can start by editing the following [file](https://github.com/OvidijusParsiunas/deep-chat/blob/2a9b6921ad7d39570ef5f4a8eae3d41d403bd8c9/component/src/views/chat/input/buttons/microphone/recordAudio.ts#L7). Let me know if you need any further help!

HI @OvidijusParsiunas  I have found the issue. It was a problem with my code. Sorry for bothering you. Thank you for your help. Thank you.

**Comment by cheresanford** [comment]
> > Hi @delsoul6104. I would recommend you to fork/clone the repository and run it locally yourself to see if you can fix the issue. It is actually very easy to do if you follow the setup guide [here](https://deepchat.dev/docs/directConnection/). You can start by editing the following [file](https://github.com/OvidijusParsiunas/deep-chat/blob/2a9b6921ad7d39570ef5f4a8eae3d41d403bd8c9/component/src/views/chat/input/buttons/microphone/recordAudio.ts#L7). Let me know if you need any further help!
> 
> HI @OvidijusParsiunas I have found the issue. It was a problem with my code. Sorry for bothering you. Thank you for your help. Thank you.

@delsoul6104 Hello! What exactly was the problem on your code? I'm running into the same issue as you, my server recognizes the file type as video/webm even though the front end at deep-chat shows it's audio/mp3. When uploading the saved file into a website that recognizes file types it also shows video/webm.
My Vue deep-chat template has this prop: `:microphone="microphoneStyles"`

Where microphoneStyles is an object with style stuff and nothing else:

`      microphoneStyles: {
          "button": {
              "position": "inside-left",
              "default": {
                  "container": {
                      "default": {
                          "borderRadius": "50%", // Round container
                          "width": "50px", // Increased width
                          "height": "50px", // Increased height
                          "display": "flex",
                          "alignItems": "center",
                          "justifyContent": "center",
                          "position": "absolute", // Position absolutely
                          "bottom": "25%" // Adjust as needed
                      },
                      "hover": {
                          "borderRadius": "80%"
                      },
                      "click": {
                          "backgroundColor": "#4d004d"
                      },
                  },
                  "svg": {
                      "styles": {
                          "default": {
                              "fontSize": "1.5em", // Increased icon size
                              "margin": "15%", // No margin
                              "filter": "brightness(0) saturate(100%) invert(49%) sepia(53%) saturate(6895%) hue-rotate(200deg) brightness(101%) contrast(101%)"
                          },
                          "hover": {
                              "filter": "brightness(0) saturate(100%) invert(73%) sepia(82%) saturate(5654%) hue-rotate(248deg) brightness(103%) contrast(99%)"
                          }
                      }
                  }
              },
              "active": {
                  "container": {},
                  "svg": {
                      "styles": {
                          "default": {
                              "filter": "brightness(0) saturate(100%) invert(49%) sepia(99%) saturate(477%) hue-rotate(343deg) brightness(100%) contrast(101%)"
                          }
                      }
                  }
              }
          }
      },`
