### ISSUE TITLE
Hey Deep-chat how do I send the dynamic values from user input which will be passed as parameter to api created and also please clarify whether it supports typescript??

### ISSUE THREAD

**Issue by SDivya31** [OvidijusParsiunas/deep-chat#207]

**Comment by OvidijusParsiunas** [comment]
Hi @SDivya31.

I am quite confused by what you mean by _send the dynamic values from user input_. By default, the user inputs are sent to the target API via the [request](https://deepchat.dev/docs/connect#Request) body. You can inspect them via the [requestInterceptor](https://deepchat.dev/docs/interceptors#requestInterceptor). If this did not answer your question please provide more info. Thanks!

You can check out the documentation [here](https://deepchat.dev/docs/introduction) and code examples [here](https://deepchat.dev/examples/frameworks).

To answer your second question for if Deep Chat supports Typescript. The answer is _Yes_.

**Comment by OvidijusParsiunas** [comment]
Since there has been no further communication, I will be closing this issue. Thanks!
