### ISSUE TITLE
Implement Context-Based Mention Suggestions with "@"

### ISSUE THREAD

**Issue by marcoserafini2** [OvidijusParsiunas/deep-chat#209]
### Description

I would like to propose the implementation of a feature similar to ChatGPT, where typing the "@" character shows a list of suggestions or mentions. This would improve the user experience, allowing for easy mention of other users or commands.

###  Requested Features
When the user types "@", a context-based suggestion list should appear.
The list should include usernames, commands, or other relevant entities.
The suggestions should update in real-time as the user types.

### Usage Examples
Typing "@" followed by the first few letters of a username should show a list of matching users.
It could also be used to suggest specific system commands, improving navigation and accessibility of available functions.

### Benefits
Makes the use of commands and additional functionalities more intuitive.
Screenshot / Mockup

1. ![image](https://github.com/OvidijusParsiunas/deep-chat/assets/7883694/5f98e12a-9e28-4046-8d40-84e4ce86e5a6)
2. ![image](https://github.com/OvidijusParsiunas/deep-chat/assets/7883694/7eb5602d-8cf8-4cac-ba03-c8b4fa76420e)

**Comment by OvidijusParsiunas** [comment]
Hi @marcoserafini2.
As cool as this sounds there are currently have a lot of planned features with a higher priority and with the limited time that I recently have it will be difficult to implement it in the near future.

If you would like to have a go at implementing it yourself, you can fork/clone the project and follow the [set up instructions](https://www.npmjs.com/package/deep-chat#construction_worker-to-create-your-own-deep-chat-component) which are very simple.

Apologies for not being able to commit to this feature, but we may consider adding it in the future.

Thankyou!
