### ISSUE TITLE
Support for Phoenix & Phoenix Live View

### ISSUE THREAD

**Issue by insidesmart** [OvidijusParsiunas/deep-chat#21]
I just saw example code for impressive number of Frameworks/Servers in the document site. Nice work.

I have following questions.

1) Is the web component framework compatible with phoenix framework ?  

2) Is the web component framework compatible with phoenix live view framework ?  
   - A small intro about phoenix live views in case you have not used it before - a thin js code is sent with server render pages with a persistent socket connection to server. For any user events, only efficient diffs of changed data/html are sent from server via existing sockets which will then make ui changes in the page.  

It would be awesome to use deep chat with phoenix & live views to leverage the best of both worlds.

If not now, may be in the future, these integrations can be explored. Looking forward to use it.

**Comment by insidesmart** [comment]
For (1) I stumbled on to this project - https://github.com/launchscout/live_state

This probably could help in integration of phoenix.

**Comment by OvidijusParsiunas** [comment]
Hi @insidesmart, thankyou for raising this issue.

I have unfortunately never used Elixir, but if Phoenix supports [web components](https://developer.mozilla.org/en-US/docs/Web/API/Web_components)/[shadow elements](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM) I don't see why Deep Chat wouldn't work on it.

My current internet connection is pretty bad so I can't download/install Elixir's ecosystem at the moment, but once I get a chance I'll let you know.

One thing that is for certain is that Deep Chat cannot be rendered in build time when using SSR as it needs access to the window/document properties that only exist in the browser, so it would need to be conditionally rendered in the UI with code that would look something like this:

```
<%= if should_render_component? do %>
  <%= raw(~S"""
    <deep-chat></deep-chat>
  """) %>
<% end %>
```

If you have Elixir/Phoenix installed, you could try it on your device and let me know if it works.
Once I get it on mine I can do a little more tinkering with it and if it all goes right I can update the website/repo with exemplar code.

**Comment by OvidijusParsiunas** [comment]
Hi. I was finally able to get Phoenix LiveView setup on my computer and am happy to say that Deep Chat works right out of the box!

Steps:

1. In your Phoenix LiveView project navigate to the `assets/` folder and there run the following command: `npm install deep-chat`
2. Inside the `assets/js/app.js` file, add the following line of code: `import "deep-chat"`
3. You can then embed Deep Chat in any of your `.ex` or `.heex` files via `<deep-chat></deep-chat>`.

To note, my expertise in Elixir/Phoenix is extremely limited, hence I did not have enough knowledge on how to correctly pass values inside its properties which is 100% possible.
Additionally, I noticed that the component style was disappearing after other components' state was changed, hence the styling will need to b set manually.

Overall Deep Chat does work as expected. I would love to have a sample project inside our repo's `example-servers` directory, however I do not have the expertise to make an exemplar project that Elixir devs could use and would need someone with a little bit of knowledge on the subject to contribute it instead. I will probably raise a new issue with `help wanted` to see if anyone can provide a simple project for this.

I will be closing this issue now. Thankyou for your efforts!

**Comment by OvidijusParsiunas** [comment]
I have created the following issue for reference:
https://github.com/OvidijusParsiunas/deep-chat/issues/38
