### ISSUE TITLE
Qestion: [fade-in effect]

### ISSUE THREAD

**Issue by GIOVANNI-75** [OvidijusParsiunas/deep-chat#211]
Hi, I wanted to know if it was possible with the implementation of the current version to add a @KeyFrame and a fade-in opacity effect to each char received in handler stream.

**Comment by OvidijusParsiunas** [comment]
Hey @GIOVANNI-75.

Just saw that you closed the issue before I could get to it. My sincere apologies as I am very busy with my work and had very little free time recently.

After having read issue description I would lean towards that this is not possible to do via the APIs provided. However, I wanted to ask if you were able to find a work around for it.

Thanks!
