### ISSUE TITLE
streaming in WebSocket mode

### ISSUE THREAD

**Issue by ronald888** [OvidijusParsiunas/deep-chat#212]
I'd like to use deep-chat with a websocket connection.
However, I'd like the response from the server to be handled similar to streaming data - chunks will be shown on the same bubble.
Currently, as chunks arrive, they are on separate bubbles.

I had configured with this:
request='{"url": "ws://customapi.com", "websocket": true}'

I added stream=true (and even assigned simulation = true and 6 as well)

Is this possible? Or I should use the Handler? 
Apologies if this question has been raised already. Unfortunately I couldn't find anything.

Thanks

**Comment by OvidijusParsiunas** [comment]
Hi, this is possible.
If your websocket responses contain full text and you simply want them to be populated as if they are in a stream, all you need to do is use the `simulation` property inside [`stream`](https://deepchat.dev/docs/connect#Stream).

However if you have a websocket connection and want individual responses to update a message bubble, please see the following issue which discusses how this can be done using the [`connection handler`](https://deepchat.dev/docs/connect#Handler) function.

**Comment by ronald888** [comment]
Thank you
