### ISSUE TITLE
Chat Rerenders and React Hooks

### ISSUE THREAD

**Issue by fragakos** [OvidijusParsiunas/deep-chat#218]
Correct me if I am wrong, but when I use any hook that triggers a rerender, the chat loses its history, but only the one that is showing, the actual history is still stored, how to overcome this?

**Comment by OvidijusParsiunas** [comment]
Hi @fragakos.

If the component that Deep Chat is defined in gets re-rendered then then the Deep Chat element will indeed be reinitialised from scratch along with its history.

I am not sure what you mean by _the actual history is still stored_ as the state in Deep Chat is refreshed.

This problem can be overcome by storing the messages inside an external state. This has been explained in more detail in the [following issue](https://github.com/OvidijusParsiunas/deep-chat/issues/154) and any further questions in regards to React re-renders should be addressed there.

Thankyou!
