### ISSUE TITLE
Are there any events to capture when we drop files in deep-chat view

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [OvidijusParsiunas/deep-chat#223]
We use deep chat and would like to customize the functionality according to our needs. We want to allow the users to drag and drop the files into the deep-chat view/section/window. We want to perform some custom functionality before sending it to deep chat. Is it possible to capture events other than onNewMessage, onClearMessages, onComponentRender, or onError?

**Comment by OvidijusParsiunas** [comment]
Currently there is no way to listen to the drag and drop file events. However, you can insert your listener _functionality_ logic into the [requestInterceptor](https://deepchat.dev/docs/interceptors#requestInterceptor) property.

If this does not meet your requirements I would then recommend forking/cloning this repo and following the [set up instructions](https://www.npmjs.com/package/deep-chat#construction_worker-to-create-your-own-deep-chat-component) to set up your own Deep Chat version which is very simple. From there you should be able to change the logic to your liking.

Thankyou!

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue since there has been no further communication.
