### ISSUE TITLE
Formatting in input message is lost on send 

### ISSUE THREAD

**Issue by terrellbm** [OvidijusParsiunas/deep-chat#226]
Hi! I've noticed in deep chat, the formatting of an input (e.g., new lines, bullets) is lost when hitting send (see video below) 

Is there any way I can preserve this formatting in the input message? 

I've looked at the output from interceptors like below, and the body seems to lose the new lines: 
```
chatElementRef.requestInterceptor = (requestDetails) => {
  console.log(requestDetails); // printed above
  requestDetails.body = {prompt: requestDetails.body.messages[0].text}; // custom body
  return requestDetails;
};
```

Output: 
```
{"body":{"messages":[{"role":"user","text":"- Item A- Item B- Item C"}]},"headers":{"Content-Type":"application/json"}}
```

Video: https://github.com/OvidijusParsiunas/deep-chat/assets/121141878/ffeb1bb9-3444-45e7-a7e7-3cd88b8733de

**Comment by OvidijusParsiunas** [comment]
Hi @terrellbm.
The fix for this is available in the latest Deep Chat `dev` version. See the following issue that addresses this:
https://github.com/OvidijusParsiunas/deep-chat/issues/165

Thanks!

**Comment by terrellbm** [comment]
Oops missed that -- thanks for pointing me in the right direction, @OvidijusParsiunas!
