### ISSUE TITLE
Display issues when code is inserted in the user's prompt

### ISSUE THREAD

**Issue by ki-zeitalter** [OvidijusParsiunas/deep-chat#227]
Hi team!

Currently we are working on an assistant that accepts code, e.g. Python-Code, from the user in the prompt. For the code highlighting we integrated highlight.js like described on your page and it works perfectly when the LLM returns code.

Unfortunately the highlighting doesn't work very well in the user's prompt:

![deepchat-highlightjs](https://github.com/OvidijusParsiunas/deep-chat/assets/136481288/fa01a61e-e6d2-427d-82d3-d3c98a458187)

Somehow the first line is ignored and is not part of the format. I know this might be more related to highlight.js than to DeepChat, but maybe you have an idea or advice for this.

Edit: I forgot to mention, that we are using deep-chat-react-dev: 9.0.183

(I want to thank you for this fantastic component!)

**Comment by OvidijusParsiunas** [comment]
Hi @ki-zeitalter.
Thankyou for razing the issue. I had another look at the DeepChat configuration for [`remarkable.js`](https://www.npmjs.com/package/remarkable) and made a change that should fix new line and code rendering issues.
This is available in `deep-chat-dev` and `deep-chat-react-dev` packages versions `9.0.185`.

So when I insert the following text into the input:
<img width="324" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/18709577/060a5610-3051-4dc8-ae04-91d236aa3fe3">

I get the following result:
<img width="321" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/18709577/e56f35bb-4233-4644-bc48-a7ea248e457b">

Let me know if this fixes your issue.

**Comment by ki-zeitalter** [comment]
Thank you for your quick reaction! Unfortunately it doesn't seem to help... Maybe the way I'm trying to use it is wrong.

When I simply paste the code into the prompt input field, without any foreword and no triple-ticks ```, then it looks like this:

<img width="896" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/136481288/1b071cee-7466-4b1f-8c34-d2c20f3bf1f2">


Otherwise, when I start with the words "Please analyse...." then it is able to recognize the beginning of the code block:

<img width="844" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/136481288/e5358871-fc55-4b57-b74b-9abbbd058b8f">

Like I said, maybe this is a case where the automatic code recognition can't work.

**Comment by OvidijusParsiunas** [comment]
I see. [remarkable.js](https://www.npmjs.com/package/remarkable) appears to be doing its best to automatically identify the code and can unfortunately recognise a portion of it. Using the triple back-tick syntax ``` is a typical way of defining code in Mark Down, hence your users would need to use it if they want to make sure that the code is rendered correctly.

You can experiment more in the [remarkable.js playground](https://jonschlinkert.github.io/remarkable/demo/)

Unfortunately any further work is down to the [remarkable.js](https://www.npmjs.com/package/remarkable) and not Deep Chat. Apologies if this causes issues for you.

**Comment by ki-zeitalter** [comment]
Thank you anyway! I was afraid it was such a thing.
