### ISSUE TITLE
Forcibly Cancel Recording Status

### ISSUE THREAD

**Issue by delsoul6104** [OvidijusParsiunas/deep-chat#229]
Is there a way to forcibly cancel the recording status?

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/20633031/da4d672a-d531-4cdb-8186-be8a30fff466)

**Comment by OvidijusParsiunas** [comment]
Hi @delsoul6104.

If you are referring to the ability of cancelling the recording button programmatically, this is unfortunately currently not available in Deep Chat.

However, given that there is an interest for this, I may add a method for it in the future.

Currently, see the following issue for possible solutions:
https://github.com/OvidijusParsiunas/deep-chat/issues/221

Any further updates should also be tracked there.

Thankyou.
