### ISSUE TITLE
Is there any way to get to enable GPT to access to the internet? Can't do that even I'm on GTP-4o

### ISSUE THREAD

**Issue by simonator1001** [OvidijusParsiunas/deep-chat#230]
As title, using 4o for chat completion, not sure if there's any other better way to do this? Thanks!

**Comment by OvidijusParsiunas** [comment]
Hi @simonator1001.

The OpenAI API currently does not provide the ability for a model to access / crawl the internet. If this changes, please update the ticket and let me know if anything needs to change in the Deep Chat API.

Thankyou!
