### ISSUE TITLE
Loading thread history in openAi assistant direct connect loads messages in reverse order

### ISSUE THREAD

**Issue by nivnahmias** [OvidijusParsiunas/deep-chat#235]
setting `load_thread_history` to `true` loads the messages history in a reverse order. 
reproduces in Playground with a very barebones setup.

I think the issue originates from the openAi API which returns the messages in a descending order - [link](https://community.openai.com/t/why-is-the-order-on-assistants-api-messages-backwards/606657).
This can be solved by setting the `order` parameters to `asc` - [link](https://platform.openai.com/docs/api-reference/messages/listMessages#messages-listmessages-order)

I can see that the code explicitly [reverses](https://github.com/OvidijusParsiunas/deep-chat/blob/ba378e5a973ef58379ec741f111abaea5b7df988/component/src/services/openAI/openAIAssistantIO.ts#L89) the returned messages in the openAi response, but perhaps it should just use the query parameter to avoid unexpected behavior?

**Comment by OvidijusParsiunas** [comment]
Hi @nivnahmias.
Thankyou for letting me know about this issue. I have made a fix for it locally and will release it in the main package tomorrow.
Thanks again!

**Comment by OvidijusParsiunas** [comment]
Hi, this has now been fixed in Deep Chat version [`2.0.1`](https://github.com/OvidijusParsiunas/deep-chat/releases/tag/2.0.1).
Let me know if you have any other issues with this. Thankyou!
