### ISSUE TITLE
Streaming responses doesn't work when setting the `onMessage` prop

### ISSUE THREAD

**Issue by nivnahmias** [OvidijusParsiunas/deep-chat#238]
Hey,

I have a setup with direct connection to an openAI assistant.
i've set up the following props on the `DeepChat` component :
```
...
connect={{ stream: true }}
onMessage={someCallbackFn}
...
```

i'm using the `onMessage` callback to store the message history in localstorage as to not reset/refetch message history on every re-render, which is super important for us as we want the chat overlay to still be available and interactive even when navigating around in the app (As instructed in a different [issue](https://github.com/OvidijusParsiunas/deep-chat/issues/154#issuecomment-2204077569)).
However, it seems that setting the `onMessage` callback causes response streaming to stop working. there's no loading indication (three dots message) and the message only populates when the response is fully received from the assistant.

The streaming behavior is obviously extremely important for good UX (some responses can take 10-30 seconds to complete) and having access to the `onMessage` callback is also very important since without it we have no way to effectively store history (in order to avoid re-fetching it).

I would appreciate some help with this issue!

P.S.
Thank you for this amazing project!

**Comment by OvidijusParsiunas** [comment]
Hi @nivnahmias.
I have been trying to replicate the problem on my end and everything seems to work fine for me. I have a feeling that it could be something to do with the logic inside the `someCallbackFn` function and not Deep Chat itself.
Could you perhaps share some more of the code you are using, thanks!

**Comment by nivnahmias** [comment]
> Hi @nivnahmias. I have been trying to replicate the problem on my end and everything seems to work fine for me. I have a feeling that it could be something to do with the logic inside the `someCallbackFn` function and not Deep Chat itself. Could you perhaps share some more of the code you are using, thanks!

Definitely an issue on my end with poor state management, works great!
Thanks for the quick reply!
