### ISSUE TITLE
Enabling  annotations

### ISSUE THREAD

**Issue by leonardocunha2107** [OvidijusParsiunas/deep-chat#241]
Hi, I'm using DeepChat as a frontend for a project using LLM agents.
The main feature I wanted was to be able to edit the AI messages to create a dataset for finetuning.
Is there a mostly straightforward way to do that using DeepChat? If not, would you be interested that I add this feature and could you give me some advice on how to do that?

**Comment by OvidijusParsiunas** [comment]
Hi @leonardocunha2107.

Could you elaborate on what you mean by _edit the AI messages to create a dataset for finetuning_?

Thanks!

**Comment by leonardocunha2107** [comment]
The flow I'm thinking is:

- user sends messahe through DeepChat
- backend answers with LLM response
- User is unsatisfied with the answer and edits the message or ToolCall to his liking inside DeepChat interface
- The edited message is sent to my backend where I can orchestrate and save a ChatHistory that I may use for LORA finetuning in the future

**Comment by OvidijusParsiunas** [comment]
Currently Deep Chat does not support the ability to edit/retry the responses.
The implementation would also be a little challenging to do. Are you looking to provide the ability to edit AI responses within the chat window itself?

**Comment by leonardocunha2107** [comment]
Hi @OvidijusParsiunas , sorry for the delay in the response.
Yes, I'm initially aiming to provide this feature within the chat window itself, though if you believe it to be cleaner to implement this with the callbacks available, "extension style" I'd be thankful of any hint on how to go about that

**Comment by OvidijusParsiunas** [comment]
Hi @leonardocunha2107.
If you are looking to implement it within the chat, then I would recommend you to fork/clone the repository and proceed to implement the necessary changes. Setting up the component is actually pretty easy to do and it is all documented [here](https://github.com/OvidijusParsiunas/deep-chat/tree/main/component#construction_worker-to-create-your-own-deep-chat-component).
I would recommend you to start making your changes on the [`addNewTextMessage`](https://github.com/OvidijusParsiunas/deep-chat/blob/eb6d0042f74c1a9f6ee01b714cdbee596c1ccd9b/component/src/views/chat/messages/messagesBase.ts#L54) method in the [`MessageBase`](https://github.com/OvidijusParsiunas/deep-chat/blob/eb6d0042f74c1a9f6ee01b714cdbee596c1ccd9b/component/src/views/chat/messages/messagesBase.ts) class.

**Comment by OvidijusParsiunas** [comment]
Because this is something that we are currently not going to proceed on implementing in the main packages, I will close this issue. However, please feel free to comment below if you need specific assistance in making changes for this. Thanks!
