### ISSUE TITLE
Messages being cleared on re-render

### ISSUE THREAD

**Issue by jyedlicka** [OvidijusParsiunas/deep-chat#25]
I'm running into some challenges with the react component when deep-chat is a child component. Messages are being cleared and the component seems to reset itself when a re-render is triggered on the parent component. 

For example, in the code below, the messages are cleared when the Drawer is closed and reopened. Is there a way to retain the messages/state when a re-render of the component occurs? 

```
export function App() {

    const [open, setOpen] = useState(false);

    return (
        <div className="app">
            <Button onClick={() => setOpen(true)}>Open Chat</Button>
            <Drawer
                title="Parent Component"
                width={500}
                open={open}
                onClose={() => {setOpen(false)}}
                placement = "right"
            >
                <DeepChat demo="true"/>               
            </Drawer>
        </div>
    );
}
```

**Comment by OvidijusParsiunas** [comment]
Hi @jyedlicka, thankyou for raising an issue.

To retain the chat messages - you will need to track them using the [onNewMessage](https://deepchat.dev/docs/events#onNewMessage) event property and reference them using [initialMessages](https://deepchat.dev/docs/messages/#initialMessages) property. The messages can be stored in state, global storage, db and many other places, but the simplest place is to store them inside a variable outside of the component. 

Here is a simple example where we use the `messages` variable to store an array of messages. When the `Refresh State` button is clicked - the state component state will be refreshed and the existing messages will be repopulated in the [initialMessages](https://deepchat.dev/docs/messages/#initialMessages) array. You can also track messages using React `useState`, but the only problem with that is when a new message is received and the array is updated - the component will be refreshed and the chat input will lose focus, so it may not lead to great UX, hence something outside of the component is more recommended.

```
let messages: MessageContent[] = [];

export default function App() {
  useEffect(() => {
    return () => {
      messages = [];
    };
  }, []);
  const [, setState] = useState(false);
  return (
    <div>
      <DeepChat
        demo={true}
        initialMessages={messages}
        onNewMessage={({ message, isInitial }) => { if (!isInitial) messages.push(message); }}
      />
      <button onClick={() => {setState((prev) => !prev)}}>Refresh State</button>
    </div>
  );
}
```
[LIVE EXAMPLE](https://codesandbox.io/s/deep-chat-react-retain-messages-mqjx5y?file=/src/App.tsx)

Let me know if you have any further questions.

**Comment by jyedlicka** [comment]
Perfect, thanks for pointing me in the right direction. I noticed loading bubbles are not displaying after incorporating these changes and there isn't any feedback to the user when waiting to receive the response. Any advice for getting the loading bubbles to display again?

**Comment by jyedlicka** [comment]
Perfect, thanks for pointing me in the right direction!

**Comment by assetllcsoftware** [comment]
I am not able to get the suggest button to work with this code. do you have any suggest button live examples of any kind?

**Comment by OvidijusParsiunas** [comment]
Hi @assetllcsoftware, I am not sure if I fully understand your question. Are you referring to the use of `"deep-chat-suggestion-button"` in the [Deep Chat Classes](https://deepchat.dev/docs/messages/HTML#deepChatClasses) section. If so - there is a full example how to use suggestion buttons in the [Examples](https://deepchat.dev/docs/messages/HTML#moreExamples) section at the bottom of the page.

If you are still experiencing issues, could you perhaps provide some of the code you are using or ideally a live code-sandbox (by Forking the one in my last comment).
If this problem is not related to re-rendering in React could you please create a separate issue and we can tackle it there. Thank you.
