### ISSUE TITLE
When using OpenAI chatGPT. How can i customize system_prompt.

### ISSUE THREAD

**Issue by YemaoLuo** [OvidijusParsiunas/deep-chat#255]
Hi, I wish to add some customize content in system_prompt. Hence I don't want to hard code the system_prompt. Is there any supported functions in deep chat that I can use? Thanks!

**Comment by OvidijusParsiunas** [comment]
Sorry for the late reply. What do you mean by _customize_ the `system_prompt` content.
The [OpenAI Chat](https://deepchat.dev/docs/directConnection/OpenAI#Chat) documentation details on how you can change the `system_prompt` property content to your liking. E.g:
```
<deep-chat
  directConnection='{
    "openAI": {
      "key": "your key",
      "chat": {"system_prompt": "You are a helpful assistant that can answer anything and everything"}
    }
  }'
></deep-chat>
```

**Comment by OvidijusParsiunas** [comment]
Closing this issue due to no further communication.
