### ISSUE TITLE
"chat" functionality for speech2text input enabling usage without pressing the mic button

### ISSUE THREAD

**Issue by FranzHell** [OvidijusParsiunas/deep-chat#257]
I am using the Speech To Element library via speechtotext for speech input in deep-chat, and I've noticed that many modern interfaces have moved away from requiring the user to press a microphone button to start speech recognition. Instead, they enable "hands-free" control by automatically detecting speech onset and then submitting the text i.e. after a period of silence.

Is there a way to add such functionality somehow or maybe this is already on the roadmap, or are there any plans to implement it in the future?

**Comment by OvidijusParsiunas** [comment]
Hey @FranzHell.

Apologies for not attending this issue in time. Detecting _speech_ is a pretty difficult job and additionally for a chat component to be able to _detect_ speech - the user must enable the microphone to work all the time, which is pretty bad UX.

Hence for this reason I am currently not going to pursue this, but I will re-open this issue if I'll start working on it.
Thanks!
