### ISSUE TITLE
How to modify the "lineHeight" for the "bubble" in the messageStyles property?

### ISSUE THREAD

**Issue by liang-junwei** [OvidijusParsiunas/deep-chat#26]

**Comment by OvidijusParsiunas** [comment]
Hey @liang-junwei. Thankyou for raising this issue. There is a bug in the component which I am currently working on fixing. I will update you when the fix will be released (later today). Thanks!

**Comment by OvidijusParsiunas** [comment]
This has now been fixed in package version `1.3.23`. Please let me know if this works for you and if you experience any other issues feel free to create another issue! Thanks again!
