### ISSUE TITLE
Styling of links within bubbles

### ISSUE THREAD

**Issue by ki-zeitalter** [OvidijusParsiunas/deep-chat#268]
Hi!

I'm trying to apply CSS style to links within the chat window. Since it is rendered within #shadowroot it seems to be impossible just to apply the color globally.
Is there any way the pass the style for links (<a href=...) to DeepChat?

Example (app is in dark mode and I would like to make the links more readable):
<img width="960" alt="Bildschirmfoto 2024-09-16 um 18 51 59" src="https://github.com/user-attachments/assets/d76aca88-691f-4433-ac6b-2b32a8340951">

Best regards

**Comment by michaelleungbowtie** [comment]
+1 on this, tried to nest the `& a` selector in some of the styling props and it didn't workout for me

**Comment by ki-zeitalter** [comment]
We finally got it! Use AuxiliaryStyle for it!

![image](https://github.com/user-attachments/assets/4bd5e97f-53d4-4926-ae0a-b4f04566c5e4)

**Comment by ki-zeitalter** [comment]
`auxiliaryStyle={"a:-webkit-any-link{ color: green; cursor: pointer;text-decoration: underline;}"}`
