### ISSUE TITLE
WebSocket connection does not handle stream: true

### ISSUE THREAD

**Issue by pushkin-artem** [OvidijusParsiunas/deep-chat#275]
I'm currently using the DeepChat library in my project and noticed a discrepancy in how the streaming feature works for Stream connections versus WebSocket connections. When using the connect prop with stream: true and a Stream API endpoint, the chunks are appended properly, creating a smooth streaming experience. However, when switching to a WebSocket connection with stream: true, the chunks are not handled in the same manner and are sent as separate messages.

How can I achieve the same result as with Stream, but using WebSocket?

Thank you!

**Comment by OvidijusParsiunas** [comment]
Hi @pushkin-artem.

I can see you closed the issue yourself. I wanted to ask if you were able to achieve what you were you looking for.

If you haven't yet, a great example is shown in the following [comment](https://github.com/OvidijusParsiunas/deep-chat/issues/138#issuecomment-1979917422) which showcases the use of the _end-phrase_ in the [`stream`](https://deepchat.dev/docs/connect/#Stream) simulation object that works great with websockets. Note the [`stream`](https://deepchat.dev/docs/connect/#Stream) property's documentation states _"A string value is used to act like an end-phrase for individual websocket messages that act like a stream."_. I hope this helps you!
