### ISSUE TITLE
submitAfterSilence not working!?

### ISSUE THREAD

**Issue by FranzHell** [OvidijusParsiunas/deep-chat#276]
Dear @OvidijusParsiunas,

I am trying to use _submitAfterSilence_ to enable submitting a message decoded via speechToText automatically.

As has been described in this issue: https://github.com/OvidijusParsiunas/deep-chat/issues/133

My speechToTextConfig (using vue.js 3):

`    const speechToTextConfig = ref({
      azure: {
        retrieveToken: fetchSpeechToken,
        region: "eastus",
        language: props.identifier,
        stopAfterSubmit: false,
        submitAfterSilence: true,
        stopAfterSilenceMs: 55000,
      },...`

My deep-chat component:
`      <deep-chat ref="chatElementRef" v-if="stream" demo="true" :speechToText="speechToTextConfig"
        :onMessage="handleNewMessage" :connect="getRequest"
        class="chat-container flex-1 m-2.5 border border-gray-300 rounded-lg h-[75vh]"
        :style="{ height: '100%', width: '100%' }"></deep-chat>`

The _stopAfterSubmit_ and _stopAfterSilenceMs_ properties have the expected effect of keeping the mic on after submission and not letting it time out early (only after 55s in my case). However, there is no submission happening after silence. The recognized text just stays there, waiting.

![image](https://github.com/user-attachments/assets/41c23af2-c864-4c25-a704-2126b57d1fd0)

I have tried it with both deep-chat and deep-chat-dev with the following versions, you said in above issue, it works with 2.0.0:
- "deep-chat": "^2.0.0",
- "deep-chat-dev": "^9.0.191",

I see it working in your demo, and I really dont do anything different. https://deepchat.dev/docs/speech/#SubmitAfterSilence

Do you have any clue as to why?

**Comment by OvidijusParsiunas** [comment]
Hi @FranzHell.
The use of the `stopAfterSilenceMs` in your case is quite redundant as it is something that comes as part of the [speechToElement](https://github.com/OvidijusParsiunas/speech-to-element) package which does not have the [`submitAfterSilence`](https://deepchat.dev/docs/speech/#SubmitAfterSilence) property.

If I understand correctly, all you want to do is stop the recording and submit after _55000ms_?
If that is the case, then I would simply recommend using the [`submitAfterSilence`](https://deepchat.dev/docs/speech/#SubmitAfterSilence) property as in the following config:
```
{
  azure: {
    subscriptionKey: 'resource-key',
    region: 'resource-region',
    language: 'en-US',
  },
  submitAfterSilence: 55000,
}
```

Let me know if this helps you. Thanks!

**Comment by FranzHell** [comment]
I used stopAfterSilenceMs previously to avoid the mic being deactivated, which happened to me, even with azure.

Using the submitAfterSilence outside the azure params works like a charm, thank you!

**Comment by OvidijusParsiunas** [comment]
Since this issue was resolved, I will be closing it.

Thankyou!
