### ISSUE TITLE
Enabling function calling with the `connect` property approach

### ISSUE THREAD

**Issue by qu8n** [OvidijusParsiunas/deep-chat#282]
Thank you for all your work with this library, Ovidijus.

Is it possible to enable function calling when using the `connect` property? In the docs, I only found function calling details in the [`directConnection`](https://deepchat.dev/docs/directConnection/OpenAI/#chat-functions) section.

I'm implementing Deep Chat with streaming in a Next.js App Router application.

**Comment by OvidijusParsiunas** [comment]
Hi @qu8n.

You can achieve something like function calling via the use of either the [`handler`](https://deepchat.dev/docs/connect#Handler) function or the [`requestInterceptor`](https://deepchat.dev/docs/interceptors#requestInterceptor) where you can listen to the user's submitted message and give an appropriate response.
If you want more of a back and forth communication where the server responds with a function request, before responding with the actual response, I would recommend going the [`handler`](https://deepchat.dev/docs/connect#Handler) way or even trying out the [`responseInterceptor`](https://deepchat.dev/docs/interceptors#responseInterceptor). It really depends on your particular case.

Let me know if this helps.

Thanks!

**Comment by qu8n** [comment]
Thank you!
