### ISSUE TITLE
Azure Assistant API calls are not using the proper authorization header

### ISSUE THREAD

**Issue by bruffridge** [OvidijusParsiunas/deep-chat#291]
Azure OpenAI Assistants API has a different authorization header than the OpenAI Assistants API (why I do not know). Currently, the authorization is using the Authorization: Bearer header instead of the api-key header Azure requires. I found the issue in the code and am working on a PR for this issue.

**Comment by OvidijusParsiunas** [comment]
Hey! Thankyou very much for the PR!
I merged the changes and published them in `deep-chat-dev` and `deep-chat-react-dev` version `9.0.199`. Let me know if everything works ok for you. Thanks!
