### ISSUE TITLE
How to log LLM token usage?

### ISSUE THREAD

**Issue by joewinke** [OvidijusParsiunas/deep-chat#296]
For each chat call to a LLM API there is a response object with prompt tokens, completion tokens, total tokens. I would like to log that information for performance monitoring. Is this possible with Deep Chat? I was unable to find anything in the docs or issues.

**Comment by OvidijusParsiunas** [comment]
Hi @joewinke.
To monitor the response object from your chosen LLM, you can simply use the [responseInterceptor](https://deepchat.dev/docs/interceptors#responseInterceptor).
