### ISSUE TITLE
Status of the gemini direct connection

### ISSUE THREAD

**Issue by jbogs** [OvidijusParsiunas/deep-chat#303]
It looks like the initial implementation for gemini was added but there were no further commits. Is there an update on whether it will be fully supported?

**Comment by OvidijusParsiunas** [comment]
Hi @jbogs.
That feature has been deprioritised in favour to some new features that have been raised recently.
Gemini is a popular LLM that is used by many developers, hence we are very keen to get it into Deep Chat soon. However, I cannot pinpoint the exact time when this will happen as there are quite a few features still to get through before it.
For further updated please follow the following [issue](https://github.com/OvidijusParsiunas/deep-chat/issues/113), thankyou!
