### ISSUE TITLE
make it work with css so we can make it responsive

### ISSUE THREAD

**Issue by Morriz** [OvidijusParsiunas/deep-chat#307]
After tinkering with this stuff for waaaaay too long I came to understand that web components the way they are implemented here are NOT allowing for outside css changes, therefor making it impossible to style it iteratively from a useful dev experience perspective.

Maybe I missed something? How can we use breakpoints, dark mode, all the goodies etc, to style the container?

**Comment by Morriz** [comment]
got grumpy

**Comment by Morriz** [comment]
Man, my mistake for not checking any of the DeepChat.dev website on mobile. It completely ignores mobile devices and doesn't render correctly at all. IMO a complete oversight by this library to not address this ;(

Sorry again, but I spent way too much time assuming this would be baked in, coming from a frontend perspective.

**Comment by Morriz** [comment]
next repo

**Comment by OvidijusParsiunas** [comment]
Sorry to hear Deep Chat didn't address your usecase.

May I ask what kind of styling was not being rendered/ignored on mobile? Also, what type of phone/OS/browser were you using?

Thanks!

**Comment by Morriz** [comment]
It just did not come with ANY responsiveness in the framework, and all was left to user land to fix. So nevermind, like I said before, this is an extreme hassle to whoop into shape. I had to workaround so much that I decided to go look for something developer friendly...but thanks for all the hard work anyway1
