### ISSUE TITLE
Unable to Add Feedback Button in User Chat Bubble

### ISSUE THREAD

**Issue by Nithiya2223** [OvidijusParsiunas/deep-chat#314]
I am trying to add a feedback button inside the user chat bubbles in the deep-chat component. My goal is to click the button and capture the id of the corresponding chat message for further API processing. However, the provided example in documentation using history it does not work for me. 

Code example:

html
<deep-chat
  history='[{"html": "<button>Button</button>", "role": "user"}]'
  style="height: 370px; border-radius: 8px"
  demo="true"
></deep-chat>

Kindly help me with this

**Comment by OvidijusParsiunas** [comment]
Hi @Nithiya2223.

To enforce JS interactivity in the HTML buttons, you will need to use the [`htmlClassUtilities`](https://deepchat.dev/docs/messages/HTML#htmlClassUtilities) `events` property. I can see you are embedding your config in html, however I would recommend getting access to an element reference for this instead. I am not sure which framework you are using but you can hopefully find one that suits you [here](https://deepchat.dev/examples/frameworks).

Then you can use the documentation examples, e.g:

```
<deep-chat
  history='[{"html": "<button class="custom-button">Button</button>", "role": "user"}]'
  style="height: 370px; border-radius: 8px"
  demo="true"
></deep-chat>
```

```
chatElementRef.htmlClassUtilities = {
  ['custom-button']: {
    events: {
      click: (event) => console.log(event.target.innerText)
    }
  }
}
```

In regards to _capturing the message id_, DeepChat does not have unique Ids for individual messages, therefore you may need to simply analyze the text inside the message as I have shown in the above example.

Let me know if this helps, Thanks!

**Comment by Nithiya2223** [comment]
Hi @OvidijusParsiunas I was trying to do this in angular framework. I just started with adding button in chat first using the code that i mentioned in the previous comment but i could not able to see the button. Like the button is not added only i could see is the plain chat screen.
How to do this in angular?

**Comment by OvidijusParsiunas** [comment]
Hey @Nithiya2223.
The code in the previous example won't simply work on Angular. You need to tailor your syntax to that framework. Please refer to the live setup guide [here](https://deepchat.dev/examples/frameworks#angular) which should help you get started.

Here is some more code to help you get going:

`app.component.html`
```
<deep-chat
    #elementRef
    demo="true"
    textInput='{"placeholder":{"text": "Welcome to the demo!"}}'
    [history]="history"
  ></deep-chat>
```

`app.component.ts`
```
export class AppComponent {
  @ViewChild('elementRef') chatElementRef: ElementRef<DeepChat> | null = null;

  ngAfterViewInit() {
    if (this.chatElementRef?.nativeElement) {
      this.chatElementRef.nativeElement.htmlClassUtilities = {
        ['custom-button']: {
          events: {
            click: (event) => console.log(event.target),
          },
        },
      };
    }
  }

  history = [
    { html: `<button class="custom-button">Button</button>`, role: 'user' },
  ];
}
```

**Comment by Nithiya2223** [comment]
Hi @OvidijusParsiunas 
Thank you for the example. I have a use case where I need to display feedback buttons for all responses returned from an API. Each response contains text and a unique trackId, 
for example:
{ text: "Hi, How can I help you?", trackId: "unique-id-123" }

The feedback buttons (e.g., 👍/👎) should be displayed for each response, and when a button is clicked, the corresponding trackId should be emitted from the click event. This trackId will be used in further API calls.

Could you please provide guidance or examples on how to achieve this?

**Comment by Nithiya2223** [comment]
Hi @OvidijusParsiunas any suggestions for the above use case?

**Comment by OvidijusParsiunas** [comment]
Hey @Nithiya2223.
The scope of your last question is not related to the issue that you have initially raised, therefore I will be closing this issue.

As I had previously noted _"DeepChat does not have unique Ids for individual messages"_, hence using `trackId` will not work as it is not part of the [Response](https://deepchat.dev/docs/connect#Response) type.

To note, the last question in itself is too broad to explore in GitHub Issues as I cannot present an outline for your project as most of the setup will rely on your actual project and not Deep Chat itself.

Please use the examples that I have already provided and the [website documentation](https://deepchat.dev/docs/messages/HTML#moreExamples) to help get you started. If you encounter any specific issues when trying to achieve your goal, please first check the website documentation and if something is not sufficient, you can then raise an issue and I will be able to help.

Apologies for the brief message, but the GitHub issues section is used for Deep Chat specific issues that devs are having when configuring Deep Chat.
