### ISSUE TITLE
Custom Header

### ISSUE THREAD

**Issue by nanotronic** [OvidijusParsiunas/deep-chat#34]
First, great work! 🤗

Is there a possibility of adding a header element to the chat? 
I would like to add an title and/or a button to maximize the chat window.

Best regards

**Comment by OvidijusParsiunas** [comment]
Hey @nanotronic.

Capabilities around the chat element such as minimize/expand/title/history are very much dependant on the website that the chat is embedded in, hence we leave the job of building this to the developers of the website.
I may add a custom wrapper for this in the future, but at the moment there are a lot of features I have to focus on for enhancing the capabilities of the chat itself before I can consider anything else.

Hopefully this makes sense, and if you have any queries for building the wrapper element yourself I would be more than happy to answer them. Thankyou!

**Comment by nanotronic** [comment]
That's fine. 
So I will go the route with a wrapper element. I just wanted to make sure I had not overlooked anything.

**Comment by OvidijusParsiunas** [comment]
Thankyou for your understanding. I will be closing this issue, however if you experience any problems or have other suggestions for improvements you are more than welcome to raise another issue. Thanks!
