### ISSUE TITLE
Support for Ember.js

### ISSUE THREAD

**Issue by phammer** [OvidijusParsiunas/deep-chat#35]
There is already a great list of supported frameworks. Would be great to see Ember.js support as well. Any plans?

**Comment by OvidijusParsiunas** [comment]
Hi @phammer.

Deep Chat is a [web component](https://developer.mozilla.org/en-US/docs/Web/API/Web_components), so if Ember.js supports web components it will inherently support Deep Chat.
The documentation for their support in Ember.js is quite limited and it doesn't appear to be as one of the frameworks listed in [custom elements everywhere](https://custom-elements-everywhere.com/), which doesn't look too promising. I have attempted to add `'deep-chat'` to an Ember.js hello world project but had no luck in getting the two to work. I additionally tried creating a basic [custom element](https://javascript.plainenglish.io/introduction-to-web-components-in-javascript-create-a-hello-world-web-component-e624874ec3b1) inside an Ember.js project but it was still not being picked up in the main template.

My knowledge of Ember.js is very limited hence my attempts may have been premature (ChatGPT was of no help as it was recommending the use of libraries that do not exist). If someone with experience in Ember.js could step in to offer advise on importing and running external web components that would be much appreciated, but as for myself I cannot seem to get it to run.

**Comment by phammer** [comment]
Hi @OvidijusParsiunas , 

of course, that probably works somehow. Meaning, simply looking into Ember.js and how to integrate external web components, setting up the data/event binding, etc. 

Maybe I check later. We have a React.js app and a Ember.js app. I am working more on the React.js side (prototype), but was proposing deep-chat internally overall and this is a question to be looked into.

If you manage to come up with an example, that's great. If we stick to deep-chat, maybe I might get to it later and can support.

**Comment by OvidijusParsiunas** [comment]
Thankyou for your understanding @phammer. I do not have the required Ember knowledge to create a suitable wrapper for this (and can't invest my time into it as I am working on multiple other features for Deep Chat), hence if somebody else will rise to the challenge to make a contribution I will be very happy to update the documentation.
Thankyou!
