### ISSUE TITLE
copy button and markdown format support 

### ISSUE THREAD

**Issue by wysstartgo** [OvidijusParsiunas/deep-chat#37]
Is it possible to support adding a copy button and an edit button on each dialogue message? Can the output content be parsed if it is in markdown format?

**Comment by OvidijusParsiunas** [comment]
Hi @wysstartgo. Thankyou for your interest Deep Chat. The message bubbles support markdown natively using the [Remarkable](https://jonschlinkert.github.io/remarkable/demo/) library. Here is an [example](https://deepchat.dev/docs/messages/#code-messages).

When it comes to editing or copying the text, this is very use-case specific, hence we don't plan to integrate this directly into the component at the moment as we are actively working on other features. We may integrate this in the future, however you can add this functionality yourself by creating your own web component using this [guide](https://javascript.plainenglish.io/introduction-to-web-components-in-javascript-create-a-hello-world-web-component-e624874ec3b1) or [Lit](https://lit.dev/) framework and referencing it in [`html`](https://deepchat.dev/docs/messages/HTML) responses. Or you can ofcourse build the component locally, which is very easy if you follow these [steps](https://github.com/OvidijusParsiunas/deep-chat/tree/main/component#construction_worker-to-create-your-own-deep-chat-component) and publish one yourself.

Thankyou for your interest once again! I will be closing this issue now, however if you have other suggestions or issues, feel free create new tickets. Thankyou!

**Comment by wysstartgo** [comment]
okay，Thank you very much!
