### ISSUE TITLE
Response should support arrays like initialMessages

### ISSUE THREAD

**Issue by juienpro** [OvidijusParsiunas/deep-chat#43]
Hi, 

Digging deeper with Deep Chat, I have an issue with Responses. 

The issue is that bundles of messages (from AI) are not supported, despite necessary.

Use-case: "Hey how can I help you? <button 1> <button 2> <button 3>" (4 messages), when this message is not an initial one.

I tried to circumvent the problem by setting up a responseInterceptor to post each message individually. It would work if there was a method `submitAIMessage`, but we only have a `submitUserMessage`. I didn't look in the source code yet to see if there is an undocumented method. 

Except if I missed something, I see two potential improvements:

- Response should support arrays. It would be much more flexible.
- The `submitUserMessage(message)` method might be changed to `submitMessage(message, role)`, so some bot messages can be handled client-side.

**Comment by OvidijusParsiunas** [comment]
Hey @juienpro.

There is a number of options that you can use for this:

1. Your service can respond with a `html` property that can contain as many message bubbles as you like. I would highly recommend taking a look at the [HTML](https://deepchat.dev/docs/messages/HTML) messages documentation for this and also checkout the [`Suggestion buttons`](https://deepchat.dev/docs/messages/HTML#moreExamples) example which relates to your use-case. 
2. Another option that you can use for sending back multiple messages is to use a [request handler](https://deepchat.dev/docs/connect#Handler) for websockets . This will enable you to handle the user and ai message sequence the way that you like.

Let me know if this helps you.

**Comment by juienpro** [comment]
1 is working after disabling bubble style and formatting them manually in my code. 

Thanks a lot! 

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/121452426/18af4c88-e8ed-4da8-9f06-a3735a2fb85d)
