### ISSUE TITLE
Save and Retrieve Chat Sessions

### ISSUE THREAD

**Issue by 7h360df47h3r** [OvidijusParsiunas/deep-chat#49]
### Description:
**Overview**
I would like to propose an enhancement for the ability to save chat sessions to local storage and retrieve them in sync. Currently, if a user refreshes the page, the entire chat session is lost, which can be inconvenient and disrupt the user's flow of interaction.

**Feature Description**
Save Session to Local Storage: Implement functionality that automatically saves the current state of the chat session to the browser's local storage periodically or upon specific user actions (e.g., sending a message).

Retrieve Previous Sessions: Upon returning to the chat or after a page refresh, users should be able to retrieve their previous session. This could be done automatically when the chat interface loads.

**Use Case and Benefits**

- Enhanced User Experience: Users won't lose important information or context from their chat sessions due to accidental page refreshes or browser closures.

- Convenience: This feature adds a level of convenience, allowing users to pick up right where they left off without having to start over.

**Comment by OvidijusParsiunas** [comment]
Thankyou for raising these descriptive feature proposals.

Whilst automatically tracking messages in local storage would be a great addition, there are few issues with it:
- The same website can have multiple chats (as Deep Chat is an injectable web component), hence it can become difficult to manage which chat component has which history. Especially if their number or order changes.
- The users may want to clear their history which would require an external component for this to happen.
- Tracking history can be very use-case dependant as different websites may have their own ways for tracking state, so I would not advertise as local storage being the go-forward strategy.

Based on the complexities outlined above, this option will currently not be pursued further.

Developers should use the [`onNewMessage`](https://deepchat.dev/docs/events#onNewMessage) event to track state in their platform and implement it the way they desire. The [Playground](https://deepchat.dev/playground) is actually already using [`onNewMessage`](https://deepchat.dev/docs/events#onNewMessage) to track its state via local storage.

Perhaps to help developers, I can add an example in the documentation for how to track state.

Thankyou once again for the detailed proposal and it certainly made me think about tracking state. If such a feature is important to you - you can always fork the project and tailor it to your use-case.

To note, I will be doing some work to help _load messages_ from state in the future, so state tracking should be improved.

Thanks again!

**Comment by OvidijusParsiunas** [comment]
The Playground adds a function called `newestMessages` to the [`onNewMessage`](https://deepchat.dev/docs/events#onNewMessage) property. [Link to code](https://github.com/OvidijusParsiunas/deep-chat/blob/1bb95a0008fa37712e7f5dbefd8fb1b7f0d4c12d/website/src/pages/playground/chat/playgroundChatComponent.js#L14C10-L14C10)

When `newestMessages` function is triggered it updates the `messages` property in the webpage's `config`.

The `config` is is accessed in the local storage when the user opens the app and is saved before closing.
[Code 1](https://github.com/OvidijusParsiunas/deep-chat/blob/1bb95a0008fa37712e7f5dbefd8fb1b7f0d4c12d/website/src/pages/playground.jsx#L45)
[Code 2](https://github.com/OvidijusParsiunas/deep-chat/blob/1bb95a0008fa37712e7f5dbefd8fb1b7f0d4c12d/website/src/pages/playground.jsx#L81)
[Code 3](https://github.com/OvidijusParsiunas/deep-chat/blob/1bb95a0008fa37712e7f5dbefd8fb1b7f0d4c12d/website/src/pages/playground.jsx#L174)

The Playground is a large application so the code may be a little hard to navigate, bug hopefully the above links will help!
