### ISSUE TITLE
Support buttons after an AI message

### ISSUE THREAD

**Issue by tommy-poetic** [OvidijusParsiunas/deep-chat#5]
A common chatbot pattern is to prompt the user with some preconfigured actions:

<details>
<summary>Large Image</summary>

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/125315167/d84d3edc-d5d2-451c-bbdf-5ee2ed51a202)

</details>

Is it possible for `deep-chat` to support this?

**Comment by OvidijusParsiunas** [comment]
Hi @tommy-poetic, given the current infrastructure - this would only be possible at the start before any messages are sent via the [`introPanel`](https://deepchat.dev/docs/introPanel).
However I do see your use-case as something that a lot of chat-bots require, hence I will add it to the list of features that I'll be working on. I unfortunately can't say exactly when can I get to it as there are quite a few things I'm working on at the moment, but it may be in the next couple of weeks. I will update this thread to update you on any progress.

**Comment by tommy-poetic** [comment]
The chosen answer would be displayed as a user message, and the AI's next message would either be more buttons or a prespecified message / LLM call:

<details>
<summary>Images</summary>

1. Select `Photos`

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/125315167/d2baa663-5d68-42f5-b601-9b5a0adbf50d)

2. Select `Community`

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/125315167/52212162-2014-4be5-8d63-93aa4c71cdfc)

</details>

Here's a link to this demo: https://betterbot.com/student-housing-demo/

**Comment by OvidijusParsiunas** [comment]
Thankyou for the example! I see what you are trying to achieve. I am fully on board with implementing this as a feature. It will take a bit of time before I can get to it due to other features I am working on at the moment, but I will update this thread as soon as I begin working on this, thankyou!

**Comment by OvidijusParsiunas** [comment]
Hey, just an update! Don't worry I have not forgotten about this feature and am very dedicated to doing it. One of the bigger features that I am currently working on is just taking a little longer than anticipated, but I should wrap it up sometime next week (fingers crossed), directly after that I am picking up this issue.
If you don't mind, I will temporarily close this issue as it is not currently being worked on and I will reopen it as soon as I begin the work for it. Thanks!

**Comment by OvidijusParsiunas** [comment]
Hi, thankyou for your patience, I have begun working on this feature and incorporated to a larger one for allowing developers to render their own custom elements. You can track its progress in the following [issue](https://github.com/OvidijusParsiunas/deep-chat/issues/18).

**Comment by OvidijusParsiunas** [comment]
This feature is now available using the new [messages HTML](https://deepchat.dev/docs/messages/HTML) API from version `1.3.11`.
