### ISSUE TITLE
basic question

### ISSUE THREAD

**Issue by linqingfan** [OvidijusParsiunas/deep-chat#50]
I just started looking at deep.dev and I m looking at the following example:
```
<!-- This example demonstrates how to set values via attributes and properties (recommended) -->
<!-- !!Please note that upon loading/saving this sandbox - the property values applied will not be applied without a RESTART!! -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="./src/styles.css" />
  </head>
  <script
    type="module"
    src="https://unpkg.com/deep-chat@1.4.3/dist/deepChat.bundle.js"
  ></script>
  <body>
    <h1>Deep Chat</h1>
    <!-- Attributes can be set as strings either directly on the element (demo/textInput) or via a `setAttribute` method on its reference (introMessage).
      When passing JSON objects make sure that they are first correctly stringified (use the following tool https://jsonlint.com/), functions assigned
      to properties must not have external references and all regex values are properly escaped.
      You can also pass values into the component via properties by using the element reference (initialMessages).
      -->
    <deep-chat
      id="chat-element"
      demo="true"
      textInput='{"placeholder":{"text": "Welcome to the demo!"}}'
    ></deep-chat>
  </body>
  <!-- !!Either set the script as "module" or place your code in a timeout in order to wait for the component to load -->
  <script type="module">
    const elementRef = document.getElementById("chat-element");
    // Setting value via a property (easiest way)
    elementRef.initialMessages = [
      { role: "user", text: "Hey, how are you today?" },
      { role: "ai", text: "I am doing very well!" }
    ];
    elementRef.setAttribute(
      "introMessage",
      JSON.stringify({
        text: "JavaScript demo for the Deep Chat component."
      })
    );
  </script>
</html>
```
Assuming i have set the request url, but how do I get the response message from URL request?

**Comment by OvidijusParsiunas** [comment]
Hey @linqingfan. Hope your issue got resolved.
For reference, I recommend looking at the [connect](https://deepchat.dev/docs/connect) part of the documentation for more information.

**Comment by linqingfan** [comment]
I have managed to make flask openai example to work but I don't know why there is always error after some medsag5 have been streamed.
Also the streamed text seems to repeat itself...

**Comment by OvidijusParsiunas** [comment]
The double stream error does seem to be a bug, let me see what I can do to fix it.

In regards to the _error_ you are referencing, I don't seem to be getting it on my end. Could you let me know what setup code you are using for Deep Chat and what the error is to help me get a better idea about it. Also, I am using the [example UI](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/ui) project to connect to the example server right out of the box, it might be worth to check it out.

**Comment by OvidijusParsiunas** [comment]
Never mind, I now started to get the error too. I'll look into this now.

**Comment by OvidijusParsiunas** [comment]
Ok, it appears that OpenAI's streaming functionality can sometimes return an incomplete JSON at the start or at the end which is what was causing the errors to be thrown. On the other hand it is now returning multiple choices per chunk which was causing the same message being returned multiple times as the strategy to aggregate text had to be changed.

For Python specifically - I had to also increase the`chunk_size` to `2048` as longer messages weren't fully read. You can raise this value to higher if you have longer messages.

Please check out the new code in this [file](https://github.com/OvidijusParsiunas/deep-chat/blob/main/example-servers/python/flask/src/services/openAI.py).
Thanks!

**Comment by linqingfan** [comment]
Hi Ovidjus,
I managed to stream without error message after I adjusted to 2048 instead of 1024. There are some words that are repeated. Any idea how to resolve this issue?

**Comment by linqingfan** [comment]
> Ok, it appears that OpenAI's streaming functionality can now sometimes return an incomplete JSON at the start or at the end which is what was causing the errors to be thrown. On the other hand it is now returning multiple choices per chunk which was causing the same message being returned multiple times as the strategy to aggregate text had to be changed.
> 
> For Python specifically - I had to also increase the`chunk_size` to `2048` as longer messages weren't fully read. You can raise this value to higher if you have longer messages.
> 
> Please check out the new code in this [file](https://github.com/OvidijusParsiunas/deep-chat/blob/main/example-servers/python/flask/src/services/openAI.py).
> 
> Thanks!

Hi Ovidjus,
I managed to stream without error message after I adjusted to 2048 instead of 1024. There are some words that are repeated. Any idea how to resolve this issue?

**Comment by linqingfan** [comment]
I also cannot make the multi messages to work. Is there anything wrong with my code:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="./src/styles.css" />
  </head>
  <script
    type="module"
    src="https://unpkg.com/deep-chat@1.4.3/dist/deepChat.bundle.js"
  ></script>
  <body>
    <h1>Deep Chat</h1>
    <deep-chat
          style={{borderRadius: '10px'}}
          introMessage={{text: 'Send a streamed chat message through an example server to OpenAI.'}}
          request='{"url": "http://127.0.0.1:7860/openai-chat-stream", "additionalBodyProps": {"model": "gpt-3.5-turbo"}}'
          requestBodyLimits={“maxMessages”: 10}
          stream="true"
          errorMessages={{displayServiceErrorMessages: true}}
    ></deep-chat>
  </body>
</html>
```
