### ISSUE TITLE
Ability to send multiple messages from custom backend

### ISSUE THREAD

**Issue by nishit-g** [OvidijusParsiunas/deep-chat#51]
I want to know if there is any way or hack , that i can do to send multiple messages at once or one by one, 

I am looking for something like this , 

User : Hello 
-- get chat 
AI : Hi , welcome 
AI : How may I help you ? 
AI : Hope you are well 

these 3 messages i want to send at once

**Comment by nishit-g** [comment]
Sorry my bad, i will see how to use websockets.

**Comment by OvidijusParsiunas** [comment]
Hey @nishit-g. You are absolutely correct. You can either connect to a [websocket](https://deepchat.dev/docs/connect#Websocket) or create a [request handler](https://deepchat.dev/docs/connect#Handler) that behaves like a websocket.
