### ISSUE TITLE
Is the streaming feature protocol-agnostic?

### ISSUE THREAD

**Issue by felixding** [OvidijusParsiunas/deep-chat#54]
Meaning I can stream via SSE or WebSocket? It looks like so from [the class](https://github.com/OvidijusParsiunas/deep-chat/blob/main/component/src/utils/HTTP/stream.ts) but I just wanted to confirm first.

Thanks!

**Comment by OvidijusParsiunas** [comment]
Hi @felixding. Streaming in Deep Chat is indeed protocol agnostic as it supports reading [Server Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) and can also simulate a streaming experience after received text from [regular HTTP requests](https://deepchat.dev/docs/connect#request) and [websockets](https://deepchat.dev/docs/connect#Websocket). Check-out more info in the [stream](https://deepchat.dev/docs/connect#stream) property.

If you have any further questions, let me know. Thanks!

**Comment by felixding** [comment]
Thanks for the explanation!

So in order to connect via WebSocket, I need to do something like this right?

```
<deep-chat
  id="deep-chat"
  request='{"url": "ws://ip:port/websocket", "websocket": true}'
  stream='{"simulation": true}'
  >
</deep-chat>
```

Then how am I supposed to subscribe to a WebSocket channel in deep-chat? Specifically, is there anyway to connect to a Rails ActionCable server?

**Comment by OvidijusParsiunas** [comment]
Your example is correct. Deep Chat will automatically try to establish a websocket connection using the address in the `"url"` value as soon as the component has rendered.
I personally have not used Rails before, however if Action Cable exposes a regular websocket endpoint, things should work for you right out of the box (as long as you are using the correct `"url"` ofcourse).
If it helps, we have a NodeJs code [example](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers/node/websockets) specifically for websockets that you can connect to using a `"url"` value of `"ws://localhost:8080"`. It should be a good starting point, and perhaps ChatGPT can help you translate it to your framework.
If you have any questions let me know. I will probably add a Ruby on Rails example the [`example-servers`](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers) directory in the near future to help anyone else that is using this framework.

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue, however if you have any more issues relating to the discussion above feel free to comment below, for anything - you can create a new issue. Thanks!

**Comment by felixding** [comment]
Unfortunately I haven't figured out how to stream the message via WebSocket + Action Cable.
But I want to say thank you all the same.

**Comment by OvidijusParsiunas** [comment]
I am really sorry to hear that @felixding.

If you are 100% sure your Action Cable set up is correct, then I can maybe advise you to use the [request handler](https://deepchat.dev/docs/connect#Handler) to set up your own websocket connection and use signals to communicate.

Could you also maybe tell me what errors you are getting?
