### ISSUE TITLE
Files content inside messages?

### ISSUE THREAD

**Issue by mage1028** [OvidijusParsiunas/deep-chat#57]
Hi, when I use the upload files functions, I can upload all kinds of files. So how can I get these files' content?
Thanks very much
<img width="436" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/23522436/5024d940-cf17-43a9-9071-de69d0c9da01">

**Comment by OvidijusParsiunas** [comment]
Hi, I have included new functionality inside the `deep-chat-dev` and `deep-chat-react-dev` package `9.0.91` version. These packages are exactly the same as the main ones except they just have different names. 

The [`onNewMessage`](https://deepchat.dev/docs/events#onNewMessage) event will now return a [file message](https://deepchat.dev/docs/messages/#MessageFile) that contains a new property called `ref` which is the actual file that was uploaded.
New type: `{src?: string; name?: string; type?: MessageFileType; ref?: File}`.

Let me know if this works for you.

The `dev` changes should be promoted to the main packages some-time next week.

Thanks!

**Comment by OvidijusParsiunas** [comment]
This is now available in the main packages version `1.4.5`. The [MessageFile](https://deepchat.dev/docs/messages/#MessageFile) type documentation has been updated to reflect this.

**Comment by rajeshwarpatlolla** [comment]
@mage1028 how are able to upload files?

I am able to upload only image files, when i upload pdf or any other files, its giving error.

I am using below code to upload files.

````
<deep-chat
     class="deep_chat"
     :mixedFiles="true"
     :images="true"
     :directConnection="{
       openAI: {
         key: '<key>',
         chat: { model: 'gpt-4-0125-preview', max_tokens: 2000 },
       },
     }"
></deep-chat>
````

am i missing something?

**Comment by OvidijusParsiunas** [comment]
Hi @rajeshwarpatlolla.
I am not quite sure if current _GPT-4_ models support other file formats than images (when this comment was posted). For other files, you will need to use an [OpenAI Assistant](https://deepchat.dev/docs/directConnection/OpenAI#Assistant). Make sure to first set up an assistant in the [Assistants Playground](https://platform.openai.com/assistants) which accepts files and then refer to it in Deep Chat via `assistant_id`.

**Comment by rajeshwarpatlolla** [comment]
I created assitant and gave assistant_id but still same error.
````
<deep-chat
      class="deep_chat"
      :mixedFiles="true"
      :images="true"
      :assistant="{ assistant_id: 'xxxxxx }"
      :directConnection="{
        openAI: {
          key: 'xxxxxx',
          chat: { model: 'gpt-4-0125-preview', max_tokens: 2000 },
        },
      }"
      :textInput="{ styles: { container: { padding: '10px' } } }"
    ></deep-chat>
````

Do you have any functioning code samples to help me identify what I might be overlooking, @OvidijusParsiunas? Alternatively, if you're aware of any gaps in the provided code, please inform me.

**Comment by OvidijusParsiunas** [comment]
Hi, you need to use the following configuration:

```
<deep-chat
  :mixedFiles="true"
  :images="true"
  :directConnection="{
    openAI: {
      key: 'xxxxxx',
      assistant: {
          assistant_id: 'xxxxxxxx',
      },
    },
  }"
></deep-chat>
```

For the assistant to handle files you will need to create it inside the OpenAI [Assistants Playground](https://platform.openai.com/assistants) and reference its id in the `assistant_id` key. To note, for your assistant to parse files you will need to enable the _Retrieval_ option:

<img width="872" alt="Screenshot 2024-04-03 at 21 53 26" src="https://github.com/OvidijusParsiunas/deep-chat/assets/18709577/3d902c93-82ef-4a21-ba1d-471c776f56e1">

I have tested this locally and it usually works fine with _images_ and _csv_ files. However, _pdf_ files are very inconsistent as it fails to read them _most_ of the time. It is really weird, but that is currently one of the downsides of recent models.

Let me know if this helps. Thanks!

**Comment by OvidijusParsiunas** [comment]
Another piece of advice I have is: try out the new assistant yourself inside the actual [Assistants Playground](https://platform.openai.com/assistants) as the issues with file uploads may be caused by OpenAI API and not Deep Chat itself.

You can also use your browser's Development Console to inspect what the error is.

<img width="306" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/18709577/ae007b42-b18d-4dc8-aab3-2664f1f29f99">

<img width="1304" alt="image" src="https://github.com/OvidijusParsiunas/deep-chat/assets/18709577/99c16f09-1146-42b9-8862-cbd0935e7f43">

**Comment by rajeshwarpatlolla** [comment]
Thank you @OvidijusParsiunas for your response. Now the file upload is working fine, but irrespective of the file I am uploading it is not able to parse or understand the files. Am I missing any additional configuration?

<img width="1387" alt="Screenshot 2024-04-08 at 19 31 04" src="https://github.com/OvidijusParsiunas/deep-chat/assets/9896335/d0751a0c-1f8f-45b2-bda6-32492f3ca44b">

**Comment by OvidijusParsiunas** [comment]
Hi @rajeshwarpatlolla.
Would you mind testing this out in the [Assistants Playground](https://platform.openai.com/assistants). If uploading files works for you in there, then I can see if there is a potential issue with Deep Chat. But I have personally tried to upload pdfs in the playground lately and have not had much success, hence I think there could be an issue with OpenAI side of things.
