### ISSUE TITLE
Dynamic import in next.js (13 with pages) - can't get reference?

### ISSUE THREAD

**Issue by johnrisby** [OvidijusParsiunas/deep-chat#59]
Hi,

I followed the framework for next.js using the dynamic import, but I just can't get the ref from the component.

If I change to a direct import - and change nothing else - it works fine. I can send messages, clear messages etc

But once I use dynamic import, it just doesn't work. 

I've been at this for hours now and tried all sorts, including direct imports with checks to only render in a browser etc but for some reason that's still causing issues, so I go back to the dynamic import and lose the ref.

I've tried several things now including useForwardRef with a wrapper etc, but nothing is working.

I noticed the next.js framework sample didn't use the ref for the component either. 

How can I do this please?

Thanks

**Comment by OvidijusParsiunas** [comment]
Hi @johnrisby. Thankyou for raising this issue and I am sorry you were experiencing such problems.
NextJs is indeed a little tricky for getting a reference to a dynamically imported component.

Here are two most straightforward ways you can get a reference:
1. You can simply add a wrapper element around the DeepChat element and reference it instead. Then, use `ref.current.children[0]` to access the DeepChat component:
```
const ref = React.useRef(null);
useEffect(() => {
  setTimeout(() => {
    ref.current.children[0].initialMessages = [
      {role: 'user', text: 'Hi'},
      {role: 'ai', text: 'Bye'},
    ];
  });
}, []);

return (
  <>
    <main className={styles.main}>
      <div ref={ref}>
        <DeepChat demo={true} />
      </div>
    </main>
  </>
);
```

2. Construct a custom `wrapper` component. Here the component is not available immediately and you may need to set a timeout if you want to access its properties right from the get-go. I got this solution from the following [comment](https://github.com/cookpete/react-player/issues/1455#issuecomment-1207154843).

index.ts file:
```
  const DeepChatWrapper = dynamic(() => import('./wrapper'), {
    ssr: false,
  });

  const ref = React.useRef(null);
  useEffect(() => {
    setTimeout(() => {
      ref.current.initialMessages = [
        {role: 'user', text: 'Hi'},
        {role: 'ai', text: 'Bye'},
      ];
    }, 40);
  }, []);

  return (
    <>
      <main className={styles.main}>
        <DeepChatWrapper demo={true} chatRef={ref} />
      </main>
    </>
  );
```

wrapper.tsx file:
```
import {DeepChat} from 'deep-chat-react';
import React from 'react';

export default function Wrapper({chatRef, ...props}) {
  return <DeepChat {...props} ref={chatRef} />;
}
```

Let me know if you need any other help with this.

**Comment by johnrisby** [comment]
Thanks @OvidijusParsiunas ! I did try a wrapper and forwardRef but that didn't work. Maybe it's the timing issue.

I have to be honest though, relying on something with a delay is never comfortable. In fact, I just had an instance where it seemed to stop working and I refreshed a few times, same, then changed the delay to 100 and it worked... I'm in dev mode so maybe that's it but ...

Also I'm using typescript. I've sorted out the ref part ok, but for the props being passed to DeepChat in the wrapper, I'm struggling and getting typescript warnings on 

 onNewMessage={({ message, isInitial }) => {
 
 (using your code for saving and restoring messages)
 
I've tried to set the type but I'm getting confused because of the two libraries. I'm importing the type from the main library as I've seen elsewhere ie

`import { DeepChat as DeepChatType } from 'deep-chat'; `

but still I'm having trouble getting the wrapper to accept the props. Any ideas please? Thanks again, so good to get it going at least!

**Comment by johnrisby** [comment]
Thanks again for that. I spent some more time on it but still wasn't comfortable with the way it was working with next.js. After a few long sessions with co-pilot and gpt4 etc as well, "we" tried everything and I realised that - for my immediate need - I was wasting my time. As I've got a (VERY) short deadline and my needs right now are simple, I've done my own basic UI which means I can move on with getting this out of the door. But I will keep an eye on this project (will star now actually) as it looks good and, as importantly, friendly and helpful replies. Best wishes

**Comment by OvidijusParsiunas** [comment]
Sorry to hear that and best wishes for your project.
May I ask what particular aspect wasn't working for you in regards to your implementation, just so I know what there is to improve on.

**Comment by OvidijusParsiunas** [comment]
For future readers:
If you have read my [first comment](https://github.com/OvidijusParsiunas/deep-chat/issues/59#issuecomment-1836516426) and have chosen to use option 2, to get around setting an arbitrary timeout, you can alternatively use the following code:

```
import {DeepChat as DeepChatCore} from 'deep-chat';
import styles from '../styles/Index.module.css';
import dynamic from 'next/dynamic';
import React from 'react';

export default function IndexPage() {
  const DeepChatWrapper = dynamic(() => import('./wrapper'), {
    ssr: false,
  }) as React.ComponentType<Partial<DeepChatCore> & {chatRef: any}>;

  const ref = React.useRef(null);

  let isSet = false;

  return (
    <>
      <main className={styles.main}>
        <DeepChatWrapper
          demo={true}
          chatRef={ref}
          onComponentRender={() => {
            if (!isSet) {
              ref.current.initialMessages = [
                {role: 'user', text: 'Hi'},
                {role: 'ai', text: 'Bye'},
              ];
              isSet = true;
            }
          }}
        />
      </main>
    </>
  );
}
```

Explanation:
You can listen to the [`onComponentRender`](https://deepchat.dev/docs/events#onComponentRender) event to get the time when the component has rendered and immediately execute the required code on the reference. This event is triggered when component properties are set with new values, hence to avoid recursion - you can use an `isSet` variable.

**Comment by OvidijusParsiunas** [comment]
Don't worry at all! I've been exactly where you have been and understand the rush of getting something to work before the deadline. Deep Chat has been specifically built to get a chat up and running quickly, and it is unfortunate that it did not do that given such a critical time for you. I understand that you are close to your deadline so I'll let you focus on your current priorities, but nonetheless I would be more than happy to hop on a quick call for a couple of minutes to see if I can help you resolve your problems (even after your project has been delivered). Feel free to email me at oparsiunas@googleamail.com

In regards to the points:
1. The type discrepancy is really good feedback and I will change it to make it all consistent.
2. Because Deep Chat is a web component, unfortunately it can only be rendered in the browser. This is an inherent issue with web components as browser variables like `window` are not available during server rendering. Hence, this limitation is a problem for all web components.
3. and 4. The use of the [`onComponentRender`](https://deepchat.dev/docs/events#onComponentRender) event could potentially fix this problem.
5. I'll update the examples (or add a reference) to this discussion to help devs get a reference to the component.

Thankyou once again for the feedback @johnrisby, and I'll continue to help you with any Deep Chat endeavours.

**Comment by OvidijusParsiunas** [comment]
Here are three most straightforward ways you can get a reference to the component in NextJs:

1. You can simply add a `wrapper element` around the DeepChat element and reference it instead. Then, use `ref.current.children[0]` to access the DeepChat component:
```
const ref = React.useRef(null);
useEffect(() => {
  setTimeout(() => {
    ref.current.children[0].initialMessages = [
      {role: 'user', text: 'Hi'},
      {role: 'ai', text: 'Bye'},
    ];
  });
}, []);

return (
  <>
    <main className={styles.main}>
      <div ref={ref}>
        <DeepChat demo={true} />
      </div>
    </main>
  </>
);
```

2. a. Construct a custom `wrapper component`. The component in this solution is not available immediately and you may need to set a timeout if you want to access its properties right from the get-go. I got this solution from the following [discussion](https://github.com/cookpete/react-player/issues/1455#issuecomment-1207154843).
**If you need to use the reference immediately when the component has rendered and do not want to use a timeOut, see solution in 2. b. below**

index.ts file:
```
  const DeepChatWrapper = dynamic(() => import('./wrapper'), {
    ssr: false,
  });

  const ref = React.useRef(null);
  useEffect(() => {
    setTimeout(() => {
      ref.current.initialMessages = [
        {role: 'user', text: 'Hi'},
        {role: 'ai', text: 'Bye'},
      ];
    }, 40);
  }, []);

  return (
    <>
      <main className={styles.main}>
        <DeepChatWrapper demo={true} chatRef={ref} />
      </main>
    </>
  );
```

wrapper.tsx file:
```
import {DeepChat} from 'deep-chat-react';
import React from 'react';

export default function Wrapper({chatRef, ...props}) {
  return <DeepChat {...props} ref={chatRef} />;
}
```

2. b. To know when the component has rendered without having to wait for an arbitrary timeOut - use the [`onComponentRender`](https://deepchat.dev/docs/events#onComponentRender) event and immediately execute the required code on the reference. It is important to note that this event is triggered when component properties are set with new values, hence to avoid recursion - you can use an `isSet` variable.

```
import {DeepChat as DeepChatCore} from 'deep-chat';
import styles from '../styles/Index.module.css';
import dynamic from 'next/dynamic';
import React from 'react';

export default function IndexPage() {
  const DeepChatWrapper = dynamic(() => import('./wrapper'), {
    ssr: false,
  }) as React.ComponentType<Partial<DeepChatCore> & {chatRef: any}>;

  const ref = React.useRef(null);

  let isSet = false;

  return (
    <>
      <main className={styles.main}>
        <DeepChatWrapper
          demo={true}
          chatRef={ref}
          onComponentRender={() => {
            if (!isSet) {
              ref.current.initialMessages = [
                {role: 'user', text: 'Hi'},
                {role: 'ai', text: 'Bye'},
              ];
              isSet = true;
            }
          }}
        />
      </main>
    </>
  );
}
```

**Comment by OvidijusParsiunas** [comment]
I have summarised our discussion in the comments above and will be referencing this in all of our NextJs examples.
I will be closing this issue, however if you experience any more problems relating to this feel free to comment below or raise a new issue for any other related matters. Thanks!
