### ISSUE TITLE
Handling async code inside the responseInterceptor

### ISSUE THREAD

**Issue by saldea1996** [OvidijusParsiunas/deep-chat#6]
I am experiencing a problem with the responseInterceptor function when I use <deep-chat> in conjunction with Laravel Queue for handling asynchronous requests. The component doesn't seem to wait for the interceptor to complete before throwing an error for an incorrect response.

```
chatElementRef.responseInterceptor = (response) => {
        return new Promise((resolve, reject) => {
            let attempts = 0;
            function checkGeneratedText() {
                if (generatedText !== "") {
                    response.reply = generatedText;
                    resolve(response);
                } else if (attempts < 5) {
                    attempts++;
                    setTimeout(checkGeneratedText, 1000);  // Check again in 1 second
                } else {
                    reject("Timed out waiting for generatedText");
                }
            }
            checkGeneratedText();
        });
    };
```

since I am queuing the requests from our project, I need to check if the process is done and if there is a reply generated.
but instead, the default response is being processed and not the one I defined.

Thank you for your help.

**Comment by OvidijusParsiunas** [comment]
Hi @saldea1996, thankyou for notifying me about your issue!
In the current architecture, `responseInterceptor` is expected to return a synchronous response, but it appears your are returning an asynchronous promise. I'm going to check what I can change in the backend to accept promises and respond shortly.

**Comment by OvidijusParsiunas** [comment]
Small question, are you using the deep-chat or deep-chat-react package?

**Comment by saldea1996** [comment]
Thank you very much. I'm using deep-chat 1.1.8
Not the react.

**Comment by OvidijusParsiunas** [comment]
Think I have a working solution. Would you mind installing a package called `deep-chat-dev` version 1.1.18. It works exactly the same as the current one you are using, but this package exists for development purposes as I'd like to first make sure that it takes care of the problem you are experiencing before adding it to the official package.

You will need to make one small change in the `responseInterceptor` code above. Instead of using `reject`, can you use the `resolve` function and pass an error value that adheres to the [`Result`](HERE) format instead as the component will then be able to handle the error gracefully. E.g. `resolve({error: "Timed out waiting for generatedText"});`.

Here is the full code for reference:

```
chatElementRef.responseInterceptor = (response) => {
  return new Promise((resolve) => {
      let attempts = 0;
      function checkGeneratedText() {
          if (generatedText !== "") {
              response.reply = generatedText;
              resolve(response);
          } else if (attempts < 5) {
              attempts++;
              setTimeout(checkGeneratedText, 1000);  // Check again in 1 second
          } else {
              resolve({error: "Timed out waiting for generatedText"});
          }
      }
      checkGeneratedText();
  });
};
```
Let me know if this fixes the problem!

**Comment by OvidijusParsiunas** [comment]
There were some other minor fixes that I have made in the codebase along with your changes and because your code does not affect any of the original logic I have added everything to the official package in version 1.1.19.
Let me know if the new code fixes your issue, thanks!

**Comment by OvidijusParsiunas** [comment]
Did not mean to close the issue, please comment below :)

**Comment by saldea1996** [comment]
Thank you very much for your quick response. It is working and it is very helpful feature to have. thanks.

**Comment by OvidijusParsiunas** [comment]
To anyone reading this thread and using the Deep Chat version that is `1.3.0` or higher, the result object has been replaced with [`Response`](https://deepchat.dev/docs/connect#Response).
