### ISSUE TITLE
Stream mode overwriting first user message with server response

### ISSUE THREAD

**Issue by mchill** [OvidijusParsiunas/deep-chat#62]
I'm experiencing a problem trying to use stream mode with my setup. I'm using [PrivateGPT](https://docs.privategpt.dev/) as a backend, which implements the OpenAI API. I configured the Deep Chat component like this:

```html
<deep-chat
      directConnection='{
          "openAI": {
              "key": "placeholder key",
              "chat": true
          }
      }'
      request='{
          "url": "<private-gpt-base-url>/v1/chat/completions",
          "additionalBodyProps": {
              "use_context": true
          }
      }'
      stream="true"
  ></deep-chat>
```

And then configured the onNewMessage handler to debug:
```javascript
const deepChat = this.shadowRoot.querySelector('deep-chat');
deepChat.onNewMessage = () => console.log(JSON.stringify(deepChat.getMessages()));
```

When I send the message "Hi", my server responds with "Hello! How can I assist you today?". In the console, I see:
```
[{"role":"user","text":"Hi"}]
[{"role":"user","text":" Hello! How can I assist you today?"}]
```

As you can see, the original user message was overwritten/removed, and the server response has the "user" role. If I simply remove `stream="true"`, I get the expected output:
```
[{"role":"user","text":"Hi"}]
[{"role":"user","text":"Hi"},{"role":"ai","text":" Hello! How can I assist you today?"}]
```

I'm not sure if the PrivateGPT stream response doesn't fully respect the OpenAI specs that you expect, or if there's some other problem. I don't have an OpenAI key at the moment to see if the problem is specific to PrivateGPT. If you have an idea what could be wrong, or have some tips for where to look, I'd appreciate it!

**Comment by OvidijusParsiunas** [comment]
Hi @mchill. Thankyou for notifying me about it and from initial inspection this appears to be a bug.
I will investigate this now.

**Comment by OvidijusParsiunas** [comment]
The bug is now fixed and will be released for a new version later today.

**Comment by mchill** [comment]
Thanks, I just tested the new version and it worked!

One note, when I looked at your commit, I saw this message: https://github.com/OvidijusParsiunas/deep-chat/blob/main/component/src/utils/errorMessages/errorMessages.ts#L23
```
const INVALID_STREAM_EVENT =
  'Make sure the events are using {text: string} or {html: string} format.' +
  '\nYou can also augment them using the responseInterceptor property: ' +
  'https://deepchat.dev/docs/interceptors#responseInterceptor';
```

But as described in the docs, `responseInterceptor` doesn't work for streaming: https://github.com/OvidijusParsiunas/deep-chat/blob/main/website/docs/docs/interceptors.mdx#L100
```
This property is not enabled for [`server-sent`](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) [`stream`](https://deepchat.dev/docs/connect#stream) responses.
```

**Comment by OvidijusParsiunas** [comment]
<img width="230" src="https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif" alt="OpenAI New Features">

**Comment by OvidijusParsiunas** [comment]
Well spotted @mchill!!!!!

The interceptor methods are not triggered for incoming stream events so the error message is definitely incorrect. Thankyou for pointing that out!

I was going to make a new change for this, however the reason why interceptors were originally not being triggered was because the returned event messages did not use the [MessageContent](https://deepchat.dev/docs/messages/#MessageContent), hence the interceptor had no real purpose. But now because the messages are expected to have this format, perhaps the interceptors should be triggered. Let me think about this.

**Comment by mchill** [comment]
Personally I'd love that feature! I have a use case for adding part of the stream response to the message (PrivateGPT returns a list of sources used for a response: https://docs.privategpt.dev/api-reference/api-reference/contextual-completions/completion#contextual_completions-prompt_completion-response-choices-sources). I was going to use the `handler`, but that does require overriding a bit more code than I'd like.

**Comment by OvidijusParsiunas** [comment]
I have added this feature to the `deep-chat-dev` and `deep-chat-react-dev` packages version `9.0.94`. These packages work exactly the same as the main ones except they have a different name.
Let me know if the interceptor works for you.

**Comment by OvidijusParsiunas** [comment]
I will also close this issue as the bug has been resolved. Nonetheless we can still continue the conversation as needed.

**Comment by mchill** [comment]
Wow, you're fast! I tested the dev package and the interceptor does exactly what I need.
