### ISSUE TITLE
How to use assistant api with deep chat

### ISSUE THREAD

**Issue by humuhimi** [OvidijusParsiunas/deep-chat#66]
Hi @OvidijusParsiunas

Description:
I want to chat via assistant api but it doesn't work. Is this feature still under development?

My code:
```tsx
  const DeepChat = dynamic(
    () => import('deep-chat-react').then((mod) => mod.DeepChat),
    {
      ssr: false,
    },
  );
```
```tsx
        <DeepChat
          directConnection={{
            openAI: {
              assistant: {
                assistant_id: process.env.ASSISTANT_ID as string,
                // function_handler:
              },
            },
          }}
          request={{
            headers: { 'OpenAI-Beta': 'assistants=v1' },
            // url: '/api/openai/chat-stream',
            // additionalBodyProps: { model: 'gpt-3.5-turbo' },
          }}
          introMessage={{
            text: t('Site.botMessage'),
          }}
          stream={true}
          requestBodyLimits={requestBodyLimits}
          errorMessages={{ displayServiceErrorMessages: true }}
          style={style}
          messageStyles={messageStyles}
          textInput={textInput}
          submitButtonStyles={submitButtonStyles}
          avatars={avatars}
        />
```
Result display:

<img src="https://github.com/OvidijusParsiunas/deep-chat/assets/35215680/a5c4d313-1283-402f-9c80-51b542454054" width="500" height="500">
<img src="https://github.com/OvidijusParsiunas/deep-chat/assets/35215680/bdf73587-e80d-432d-ae16-b2da59f2c0f8" width="500" height="500">
<img src="https://github.com/OvidijusParsiunas/deep-chat/assets/35215680/f49a480d-75fe-45ec-b18f-d7fa9f601c56" width="500" height="500">

Environment:
Browser: Chrome version 119.0.6045.200
nextjs version: 14.0.2
Node.js version: v19.1.0

please check it when you have time! thank!

**Comment by OvidijusParsiunas** [comment]
Hi @humuhimi! Thankyou for informing me about this issue.

This is a bug and I will try to fix it.

I will report on the progress in this thread.

**Comment by OvidijusParsiunas** [comment]
This issue has now been fixed in the `deep-chat-dev` and `deep-chat-react-dev` packages version `9.0.95`. These packages work exactly the same except their names are different.
The changes will be moved to the main package later this week or early next week.

**Comment by OvidijusParsiunas** [comment]
This bug fix has now been released in `deep-chat` and `deep-chat-react` package version `1.4.6`.
