### ISSUE TITLE
'Error, Please try again.' displayed when using initial message

### ISSUE THREAD

**Issue by ecomnet** [OvidijusParsiunas/deep-chat#67]
Thank you for releasing this very easy to use code.

I tried to use React and test it, and the error occurs like below. 
I tested the Suggestion buttons example on https://deepchat.dev/docs/messages/HTML with a real OpenAI API key.

After a few tests, I got 'Error, Please try again' when initialMessages has 'html' in it.
If it is 'text', it works fine.

{
    html: `
      <div class="deep-chat-temporary-message">
        <button class="deep-chat-button deep-chat-suggestion-button" style="margin-top: 5px">What do shrimps eat?</button>
        <button class="deep-chat-button deep-chat-suggestion-button" style="margin-top: 6px">Can a shrimp fry rice?</button>
        <button class="deep-chat-button deep-chat-suggestion-button" style="margin-top: 6px">What is a pistol shrimp?</button>
      </div>`,
    role: 'ai',
}

Also, is there an option to make the introPanel not disappear after the message is entered?

**Comment by OvidijusParsiunas** [comment]
Hi @ecomnet. Thankyou for notifying me about this issue.
I am going to work on a fix for it.
I will update this thread on the progress.

**Comment by OvidijusParsiunas** [comment]
To answer your question about the [introPanel](https://deepchat.dev/docs/introPanel). The chat is configured to remove it, however if you want to keep it I would instead recommend you to use the [introMessage](https://deepchat.dev/docs/messages/#introMessage) with a `html` property which will stay in the chat view.

**Comment by OvidijusParsiunas** [comment]
This issue has now been fixed in the `deep-chat-dev` and `deep-chat-react-dev` packages version `9.0.95`. These packages work exactly the same except their names are different.

The changes will be moved to the main package later this week or early next week.

**Comment by OvidijusParsiunas** [comment]
This bug fix has now been released in `deep-chat` and `deep-chat-react` package version `1.4.6`.
