### ISSUE TITLE
Is there a provision to add Minimize and Maximize the chat window

### ISSUE THREAD

**Issue by prabhakar1994** [OvidijusParsiunas/deep-chat#69]
@OvidijusParsiunas Do we have a provision to add Minimize and Maximize the chat window for deepchat.

**Comment by OvidijusParsiunas** [comment]
Hi @prabhakar1994, the ability to minimize/maximise the chat component does not come with Deep Chat as it is very case speicific, therefore it should be controlled by the container element in the parent application.

**Comment by prabhakar1994** [comment]
Thank you @OvidijusParsiunas. I think this would be a good enhancement. But as you suggested (**Can be controlled by the container element in the parent application**). I have done that. Thanks again for quick help.

**Comment by OvidijusParsiunas** [comment]
Good to hear it works @prabhakar1994.
The Deep Chat project is currently focused on improving the chat component's experience as there are many features still to be introduced. Minimize/Maximise functionality would ofcourse be nice to have, but that falls under the category of *external optional components* which require a new element *outside* of the chat container that *some* users may need for their use-cases. Hence it may be released as a separate component in the future. Stay tuned for further updates on this.
