### ISSUE TITLE
Vue 2 build error

### ISSUE THREAD

**Issue by hn5092** [OvidijusParsiunas/deep-chat#7]
Module parse failed: Unexpected token (110:14)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   static processConfig(n, e) {
|     var t;
>     return e ?? (e = {}), e.disabled ?? (e.disabled = n.isTextInputDisabled), e.placeholder ?? (e.placeholder = {}), (t = e.placeholder).text ?? (t.text = n.textInputPlaceholderText), e;
|   }
|   // this is is a bug fix where if the browser is scrolled down and the user types in text that creates new line

 @ ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js& 1:0-19
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.111:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by hn5092** [comment]
same error on sandbox

**Comment by OvidijusParsiunas** [comment]
Hi @hn5092, thankyou for raising this issue! I am going to investigate this problem now and update you on the progress.

**Comment by OvidijusParsiunas** [comment]
Does this sandbox for Vue 2 work on your computer?
https://codesandbox.io/s/deep-chat-vue2-cdqpt2?file=/src/App.vue

**Comment by hn5092** [comment]
error again,  it's my sanbox, pls help me fix it , thx  https://codesandbox.io/p/sandbox/deep-chat-vue2-forked-hcpz94?file=/package.json:1,1

**Comment by hn5092** [comment]
i found it's unknow  ?? token , but i can't fix it .just  learned vue

**Comment by OvidijusParsiunas** [comment]
The issue you are having stems from the fact that vue 2 by default uses - webpack 4 which can have issues loading javascript syntax that is above ES5.
I cannot easily downgrade deep-chja to ES5

**Comment by hn5092** [comment]
牛逼!🐮🍺    thx!

**Comment by OvidijusParsiunas** [comment]
If you don't mind I'll be closing this issue, you can still comment below if you experience problems relating to this or create new issues for anything else, thanks!

**Comment by OvidijusParsiunas** [comment]
For future reference, you can track issues/solutions for building ES5/ES2015 JavaScript in the following [issue](https://github.com/OvidijusParsiunas/deep-chat/issues/9).

**Comment by OvidijusParsiunas** [comment]
Hi, this issue seems to also affect the earlier versions of Vue 3 which also use Webpack 4.
I investigated it further and managed to transpile the component into JavaScript that uses ES5/2015.

This means that you no longer need to use the above solution and can simply import `deep-chat` version `1.1.21` and use it like the normal examples.
