### ISSUE TITLE
openAI : Assistants API 

### ISSUE THREAD

**Issue by ittech17** [OvidijusParsiunas/deep-chat#73]
Hi,

Do we have plan to integrate openAI's Assistants API ?
Reference :  https://platform.openai.com/docs/assistants/overview/agents

**Comment by OvidijusParsiunas** [comment]
Hi, Deep Chat already supports a direct connection for the Assistants API. You can find all the relating information [here](https://deepchat.dev/docs/directConnection/openAI#Assistant).

**Comment by OvidijusParsiunas** [comment]
Since there has been no further discussion, I will be closing this issue. Feel free to comment below if you have any questions relating to the Assistants API. For anything else, you are more than welcome to create a new issue. Thanks!
