### ISSUE TITLE
Dynamically set additionalBodyProps?

### ISSUE THREAD

**Issue by RickGroenewegen** [OvidijusParsiunas/deep-chat#74]
Right now you can set some set values for additionalBodyProps that are the same each message to the server.

Is there a way to dynamically set these additionalBodyProps? The value I would like to pass could change with each message.

**Comment by OvidijusParsiunas** [comment]
Hi @RickGroenewegen. You can use the [requestInterceptor](https://deepchat.dev/docs/interceptors#requestInterceptor) property for this. Let me know if you need further assistance.

**Comment by OvidijusParsiunas** [comment]
Happy to hear it works.

In regards to the [responseInterceptor](https://deepchat.dev/docs/interceptors#responseInterceptor), could you elaborate on what you mean by _" ignore the messages"_? This property is used to augment the incoming responses to fit the [format](https://deepchat.dev/docs/connect#Response) that Deep Chat is expecting. Hence, it will not be useful to ignore messages.

If you are working with a [websocket](https://deepchat.dev/docs/connect#Websocket) connection, then responses can be ignored via the use of a [handler](https://deepchat.dev/docs/connect#Handler) function where you'll need to define the connection code yourself (which is not hard) and hence control what messages go to Deep Chat.

Let me know more about your use-case, what configuration you are using and what kind of responses you are working with to give you the right pointers. Thanks!

**Comment by RickGroenewegen** [comment]
I meant that I have one WS server, but this server sends both chat messages (Intended for Deep Chat), and application messages (Custom messages for my application which do not follow the Response) type. Deep Chat currently throws errors on those last type of messages.

I though I might be able to use the responseInterceptor to return the valid Deep Chat messages and pass other messages on to my custom application. But since the responseInterceptor must always return a Response I think this is not possible?

I am not sure what you means by defining the connection code myself. Do you suggest I create my own WS connection and when I receive a Deep Chat message I am able to pass it on to Deep Chat? How would I do that? Because I see the addMessage method is no longer available?

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue since there has been no further communication. However, if you need any assistance in the topic of this thread feel free to comment below, otherwise you can raise a new issue. Thanks!
