### ISSUE TITLE
How to connect to an API ,Come across a problem

### ISSUE THREAD

**Issue by 2531800823** [OvidijusParsiunas/deep-chat#77]
When I use  chat GPT, request body messages type  {role:'user|system',content:'text'}[] , So how can the configuration be adapted

**Comment by 2531800823** [comment]
Interceptors  can be realized

**Comment by OvidijusParsiunas** [comment]
That is correct, [interceptors](https://deepchat.dev/docs/interceptors) are best for working with custom endpoints :)
