### ISSUE TITLE
Amazon Bedrock Integration

### ISSUE THREAD

**Issue by devpulse01** [OvidijusParsiunas/deep-chat#79]
Hey Ovidijus,
Would it be possible to integrate Amazon Bedrock with Deep-chat?
Reference: https://aws.amazon.com/fr/bedrock/

Thank you,
Best

**Comment by OvidijusParsiunas** [comment]
Hi @devpulse01.

I have tried to experiment with AWS Bedrock but have encountered a problem when attempting to create a Rest Endpoint to allow Deep Chat to call it. Currently, when creating an Agent - the only models that I can choose are `Anthropic Claude`. The problem with that is my access for `Anthropic` models is not being approved, hence I can't use the Agent.

It is also worth mentioning that `Anthropic` models are not easy to get access to in general as I have tried to get access to their console a long time ago and am still not eligible to-date. I have even created a [Reddit Post](https://www.reddit.com/r/AnthropicAi/comments/18210t9/generating_api_keys/) for this.

Hopefully we can use other models in the future, but for now there is not much I can do.

Let me know if you found some other way to create an AWS Bedrock Rest Endpoint or if I am missing some information.
Thanks!

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue since there has been no further communication. However, if you need any assistance in the topic of this thread feel free to comment below, otherwise you can raise a new issue. Thanks!

**Comment by devpulse01** [comment]
Hi Ovidijus,
Sorry for the late reply. I haven't had a chance to look into this further yet.
I'll check it out and get back to you.
Thanks!

**Comment by havle** [comment]
@OvidijusParsiunas I think Claude 3 is now have open general access - maybe we could get Deep Chat to work with Claude 3 as well?

**Comment by OvidijusParsiunas** [comment]
Hey, I will begin work on the Claude implementation shortly. If all goes to plan, I will try to add the Amazon Bedrock implementation as soon as I can.
