### ISSUE TITLE
Vue 3 - error when passing values into Deep Chat

### ISSUE THREAD

**Issue by stanleyseow** [OvidijusParsiunas/deep-chat#8]
I use the following sample code below in codesandbox, got this error 

**Please define "request" with a "url"**

```
<deep-chat
  request='{
    "url": "https://customapi.com/message",
    "method": "POST",
    "headers": {"customName": "customHeaderValue"},
    "additionalBodyProps": {"field": "value"}
  }'
></deep-chat>
```

**Comment by OvidijusParsiunas** [comment]
Hi @stanleyseow, your code looks good. Would you mind letting me know which particular CodeSandbox is causing this issue?

To note, the initial loadup of CodeSandbox can sometimes be buggy and hitting the refresh button pictured below can help load it up correctly:

<img width="330" alt="Screenshot 2023-08-31 at 13 25 57" src="https://github.com/OvidijusParsiunas/deep-chat/assets/18709577/4a36ea69-6de1-4e29-8e39-f4285c21d8ff">

**Comment by stanleyseow** [comment]
https://www.npmjs.com/package/deep-chat
I just click on the **Vue3** that brings me to codesandbox and copy the below code ... 

[this url](https://codesandbox.io/s/deep-chat-vue3-7y99jq?file=/src/App.vue
)
```
<deep-chat
  request='{
    "url": "https://customapi.com/message",
    "method": "POST",
    "headers": {"customName": "customHeaderValue"},
    "additionalBodyProps": {"field": "value"}
  }'
></deep-chat>
```

**Comment by OvidijusParsiunas** [comment]
In Vue 3, component properties are defined by appending a colon ( : )  before the property name. So by adding it to `request` as `:request` will pass the value to the component's property. CodeSandbox will also automatically format the object value syntax for you, so in the end you should have:

```
  <deep-chat
    :request="{
      url: 'https://customapi.com/message',
      method: 'POST',
      headers: { customName: 'customHeaderValue' },
      additionalBodyProps: { field: 'value' },
    }"
  ></deep-chat>
```

Please note that the `https://customapi.com/message` url is only used for exampular purposes and is not a real endpoint, so if you want to test this out, I suggest using the [demo](https://deepchat.dev/docs/directConnection/demo), [directConnection](https://deepchat.dev/docs/directConnection/) properties or ofcourse running the code locally with any of the [example](https://github.com/OvidijusParsiunas/deep-chat/tree/main/example-servers) servers. For further help, the [Start](https://deepchat.dev/start) page is there to assist you on your journey.

Let me know if this helps.

**Comment by stanleyseow** [comment]
Thanks, solved.
