### ISSUE TITLE
Adapting Deep Chat dimensions to the parent application elements

### ISSUE THREAD

**Issue by 2531800823** [OvidijusParsiunas/deep-chat#80]
```tsx

export const App: FC = () => {
  return (
    <div style={{ width: 500, height: 200 }}>
      <DeepChat
        initialMessages={initialMessages}
        style={{ width: '100%', height: '100%' }}
        chatStyle={{
          width: '100%',
          height: '100%',
          borderRadius: '8px',
        }}
      ></DeepChat>
    </div>
  );
};
```

[dome](https://stackblitz.com/edit/stackblitz-starters-hkd9ur?file=src%2FApp.tsx)

**Comment by 2531800823** [comment]
Because I want him to be dynamic when I reseize. `react-resize-detector`  will cause him to repeat render ,Please help me with a good solution.  thank you!

**Comment by OvidijusParsiunas** [comment]
Hi @2531800823,
If you want the chat component to fill the dimensions of the parent element. All you need to do is use the [`'inherit'`](https://developer.mozilla.org/en-US/docs/Web/CSS/inherit) dimension values:

```
chatStyle={{
  width: 'inherit',
  height: 'inherit'
}}
```

Here is the [live](https://stackblitz.com/edit/stackblitz-starters-14utrz?file=src%2FApp.tsx) example.

Let me know if this helps.

**Comment by 2531800823** [comment]
If its parent element is 100% then it will fail。

**Comment by 2531800823** [comment]
If its parent element is 100% then it will fail。
Here is the [live](https://stackblitz.com/edit/stackblitz-starters-hkd9ur?file=src%2FApp.tsx) example.

**Comment by 2531800823** [comment]
If its parent element is 100% then it will fail。
Here is the [live](https://stackblitz.com/edit/stackblitz-starters-hkd9ur?file=src%2FApp.tsx) example.

**Comment by 2531800823** [comment]
I want to make changes in the window so that it automatically ADAPTS to the screen size。

**Comment by OvidijusParsiunas** [comment]
To help with element positioning/adaptability around other elements, you can use the [display](https://www.w3schools.com/cssref/pr_class_display.php) style property. So in this example you can use the `'block'` value:

```
chatStyle={{
  display: 'block',
  width: 'inherit',
  height: 'inherit',
  borderRadius: '8px',
}}
```

Here is a [live](https://stackblitz.com/edit/stackblitz-starters-bcxucg?file=src%2FApp.tsx) example.
Let me know if you have further questions.

**Comment by 2531800823** [comment]
thank you!

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue since there has been no further communication. However, if you need any assistance in the topic of this thread feel free to comment below, otherwise you can raise a new issue. Thanks!
