### ISSUE TITLE
Customize the chat component

### ISSUE THREAD

**Issue by AhmeedBen** [OvidijusParsiunas/deep-chat#81]
How to customize the overall look of the chat component, add a header for example?

**Comment by OvidijusParsiunas** [comment]
Hi @AhmeedBen.
To style the component content itself you can use the [`styles`](https://deepchat.dev/docs/styles) and [`messageStyles`](https://deepchat.dev/docs/messages/styles) properties. You can also view various [design examples](https://deepchat.dev/examples/design).

If you want content around the chat, like a header etc, you will have to create it yourself as those type of components are very use-case specific. We may consider creating those in the future. Thanks!

**Comment by AhmeedBen** [comment]
Thanks for the great work,
I Already see all the design examples and how to change container styles, bubble etc...
What is the mean component that has to be changed, if i want to add a custom header for eg.

**Comment by OvidijusParsiunas** [comment]
Perhaps I may have misunderstood your intent. Could you elaborate on what you mean by a _header_. Thanks!

**Comment by AhmeedBen** [comment]
I want to add custom visual elements to the chat.
<img width="285" alt="header" src="https://github.com/OvidijusParsiunas/deep-chat/assets/130488191/1e259bc0-2478-4db5-8c77-18b04b092ad8">

**Comment by OvidijusParsiunas** [comment]
I see. Deep Chat currently does not have native support for external elements around it such as a header. Hence you will have to create your own wrapper element around it and customise it to your preference.

**Comment by OvidijusParsiunas** [comment]
I will be closing this issue since external components around the chat are currently not being pursued. If you have any further questions in regards to this feel free to comment below. For anything else you are more than welcome to create a new issue. Thanks!
