### ISSUE TITLE
How do you embed this into a page?

### ISSUE THREAD

**Issue by AntDX316** [OvidijusParsiunas/deep-chat#85]
How do you embed this into a page?

**Comment by OvidijusParsiunas** [comment]
Hi @AntDX316. Can you elaborate on your question? Thanks!

**Comment by AntDX316** [comment]
I’m not sure how to integrate it into an HTML page?

**Comment by OvidijusParsiunas** [comment]
If you have a basic webpage with no framework - I would recommend checking out our [live vanillajs example](https://codesandbox.io/p/sandbox/deep-chat-vanillajs-v2ywnv?file=%2Findex.html). You should be able to pretty much copy all of the code from the _index.html_ file and place it into your page.

For everything else, I would recommend checking out our [documentation](https://deepchat.dev/docs/introduction).

**Comment by OvidijusParsiunas** [comment]
Hi, I will be closing this issue as there has been no further communication. If you need any more assistance in the context of this issue, you are more than welcome to comment below. For everything else, you can create a new issue. Thanks!
