### ISSUE TITLE
example code syntax error message

### ISSUE THREAD

**Issue by linqingfan** [OvidijusParsiunas/deep-chat#90]
![Screenshot from 2024-01-05 10-50-34](https://github.com/OvidijusParsiunas/deep-chat/assets/3726847/0a49baa0-53c5-4ef8-8742-39d0ca983e68)

Hi, I copy and paste the live vanilla JS example (https://codesandbox.io/p/sandbox/deep-chat-vanillajs-v2ywnv) and it shows some syntax errors:

Uncaught SyntaxError: Expected property name or '}' in JSON at position 1 (line 1 column 2)
    at JSON.parse (<anonymous>)
    at Object.object (deepChat.bundle.js:1:167115)
    at Hn.attributeChangedCallback (deepChat.bundle.js:1:101686)
    at deepChat.bundle.js:1:285588

The code run perfectly though.

**Comment by OvidijusParsiunas** [comment]
Hi @linqingfan.

I have tested this on my computer and it seems to work fine with no errors. Can you share the code you are using for this. Thankyou!

**Comment by linqingfan** [comment]
> Hi @linqingfan.
> 
> I have tested this on my computer and it seems to work fine with no errors. Can you share the code you are using for this. Thankyou!

I just used the index.html in the link https://codesandbox.io/p/sandbox/deep-chat-vanillajs-v2ywnv

**Comment by OvidijusParsiunas** [comment]
Yep, that is the same code that I used and no error for me. I will test this out on another machine tomorrow.

Can I also ask, how are you hosting the file, do you run a server or is it just a plain `index.html` file viewed in the browser. Also, what kind of browser and operating system are you using, versions might be useful too.

Final question, do you see any console errors (or the one that you have showed me) in the [live](https://codesandbox.io/p/sandbox/deep-chat-vanillajs-v2ywnv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpei56li00073b6ikklnz3mb%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpei56li00033b6i6rn8s6ux%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpei56li00043b6iktqgwts5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpei56li00063b6i8kxqkfoc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpei56li00033b6i6rn8s6ux%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpei56li00023b6i8rsz2f0v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clpei56li00033b6i6rn8s6ux%2522%252C%2522activeTabId%2522%253A%2522clpei56li00023b6i8rsz2f0v%2522%257D%252C%2522clpei56li00063b6i8kxqkfoc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpei56li00053b6isvj6plsq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpei56li00063b6i8kxqkfoc%2522%252C%2522activeTabId%2522%253A%2522clpei56li00053b6isvj6plsq%2522%257D%252C%2522clpei56li00043b6iktqgwts5%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpei56li00043b6iktqgwts5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) example.

**Comment by linqingfan** [comment]
I just view it on my chrome browser on Windows 11, version 22H2
Yes, the errors are shown in the console. BTW, as mentioned in the first message, I only see the error messages in the chrome console. If I dont do F12, I wont be noticing any error messages and the program is still runnable.

BTW, on another issue,  may I know if there is a way to change the conversation history when an event is activated. E.g. trying to omit the last character of the new message returned from the server.

chatElementRef.onNewMessage = (message) => { 
console.log(message); 
message.message.text = message.message.text.slice(0,-1)
};
This doesnt work.

**Comment by OvidijusParsiunas** [comment]
I have tested the code on a Windows 11 - 22H2 machine with the latest Chrome Browser (version 120.0.6099.199 to date).
I have additionally tested it on Ubuntu and Mac operating systems and once again I saw no errors in the console.

I will unfortunately have to conclude that this error is caused by the specific configuration that you have on your computer or your browser. If there is anything else that I can potentially do to replicate the error, please let me know, but because I cannot replicate it I am not be able to write a fix for it.

To answer your question for augmenting a response message, I would recommend checking out the [`responseInterceptor`](https://deepchat.dev/docs/interceptors#responseInterceptor). If you need any specific assistance with this, please create a new issue so I can help there. Thanks!

**Comment by linqingfan** [comment]
Oh yes, when I tried the same code in Linux, there is no such error message. Should be windows environment....
