### ISSUE TITLE
"Uncaught (in promise) SyntaxError" while streaming Custom API

### ISSUE THREAD

**Issue by K-Jadeja** [OvidijusParsiunas/deep-chat#96]
Thanks to the creators of this repo! It saved me a ton of time on my project

I have a FastAPI server that has stream and invoke routes. 
The invoke route works perfectly fine but I am getting this error while streaming:
`VM10203:1  Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)`
I got this error even though the text streamed perfectly on my component

I am attaching screenshots of the `console.log(details)` response and the error:
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/113630783/89c59670-3029-412f-a2e2-0814ffd89355)

Snippet from the code I used:
```const requestInterceptor: RequestInterceptor = (details) => {
    details.body = {
      input: {
        text: details.body.messages[0].text,
      },
      config: {},
      kwargs: {},
    };
    return details;
  };

  const responseInterceptor: ResponseInterceptor = (details) => {
    console.log(details);
    return { text: details.content };
  };

  return (
    <Box
      display="flex"
      justifyContent="space-between"
      alignItems="center"
      // mb={2}
    >
      <DeepChat
        request={{ url: 'http://localhost:3000/detective/stream' }}
        requestInterceptor={requestInterceptor}
        responseInterceptor={responseInterceptor}
        style={{
```

According to my online research, it seems like there is a problem with `json.parse()`-ing an empty string

Would appreciate any help,

Thanks!

**Comment by OvidijusParsiunas** [comment]
Hi @K-Jadeja.
I have looked at your code but was unable to replicate the exact issue.
The `responseInterceptor` does accept a response with empty string `text` property, so that does not appear to be the problem: e.g. `return {text: ''};`.
However, after looking at your logs, it appears that the first json response does not contain the `content` property and only has `run_id`, hence you are not return anything in text. Could you perhaps try to change the `responseInterceptor` code to return the following response:
```return { text: details.content || '' };```

Let me know if it works.

May I also ask if you are using `stream={true}` property.

Thanks!

**Comment by K-Jadeja** [comment]
Thanks for the reply,

`return { text: details.content || '' };` did not work. I still get the same exact error.

![image](https://github.com/OvidijusParsiunas/deep-chat/assets/113630783/779e5de6-6364-4e56-8e2b-6e454328c594)


Yes, I have set `stream` to true

Here's the code:
```
<DeepChat
        request={{ url: 'https://truedream.up.railway.app/test/stream' }}
        requestInterceptor={requestInterceptor}
        responseInterceptor={responseInterceptor}
        stream={true}
/>
```
and the interceptor code:
```
const requestInterceptor: RequestInterceptor = (details) => {
    details.body = {
      input: {
        text: details.body.messages[0].text,
      },
      config: {},
      kwargs: {},
    };
    return details;
};

const responseInterceptor: ResponseInterceptor = (details) => {
    console.log(details);
    return { text: details.content || '' };
};
```

**Comment by OvidijusParsiunas** [comment]
Before the response interceptor is called, the Deep Chat code performs the following operation:
```
const eventData = JSON.parse(message.data);
```

I have a feeling that this is what is causing the error as the returned [`data`](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#data) property does not contain a valid JSON.

I have created a quick fix to handle this better and to allow you to amend this via the [`responseInterceptor`](https://deepchat.dev/docs/interceptors#responseInterceptor). I will include it in the upcoming big release. However if you want to use it now, you can access it in the `deep-chat-dev` and `deep-chat-react-dev` packages version `9.0.112`. These packages are exactly the same as the main ones except their names are different.

Thanks!

**Comment by OvidijusParsiunas** [comment]
This has now been released in `deep-chat` and `deep-chat-dev` package versions of `1.4.9`.

**Comment by K-Jadeja** [comment]
Thanks @OvidijusParsiunas! That fixed it.
