### ISSUE TITLE
Issues while referencing DeepChat element

### ISSUE THREAD

**Issue by K-Jadeja** [OvidijusParsiunas/deep-chat#99]
I've been following issue #59 and am trying to wrap the DeepChat element and reference the wrapper element. I am trying to get your [first suggestion](https://github.com/OvidijusParsiunas/deep-chat/issues/59#issuecomment-1839483469) to work with my code but I am facing a lot of errors like `Property 'children' does not exist on type 'never'` and `'ref.current' is possibly 'null'.`

Sorry, I am new to typescript and would really appreciate any help getting this to work
My code:
```
import React, { useEffect } from 'react';
import Box from '@mui/material/Box';
import dynamic from 'next/dynamic';
import { useUser } from '@clerk/nextjs';
import { RequestInterceptor, ResponseInterceptor } from 'deep-chat/dist/types/interceptors';
import { DeepChat as DeepChatCore } from 'deep-chat';

const DeepChat = dynamic(() => import('deep-chat-react').then((mod) => mod.DeepChat), {
  ssr: false,
});

export const ChatComponent = () => {
  const { user } = useUser();
  const ref = React.useRef(null);

  useEffect(() => {
    setTimeout(() => {
      if (ref.current) {
        const component = ref.current.children[0] as DeepChatCore;
        component.initialMessages = [
          { role: 'user', text: 'Hi' },
          { role: 'ai', text: 'Bye' },
        ];
      }
    });
  }, []);

  const requestInterceptor: RequestInterceptor = (details) => {
    details.body = {
      input: {
        text: details.body.messages[0].text,
      },
      config: {},
      kwargs: {},
    };
    return details;
  };

  const responseInterceptor: ResponseInterceptor = (details) => {
    // console.log(details);
    return { text: details.content || '' };
  };

  return (
    <Box
      display="flex"
      justifyContent="space-between"
      alignItems="center"
      // mb={2}
    >
      <div ref={ref}>
        <DeepChat
          request={{ url: 'https://test.up.railway.app/test/stream' }}
          requestInterceptor={requestInterceptor}
          responseInterceptor={responseInterceptor}
          requestBodyLimits={{ maxMessages: -1 }}
          stream={true}
        />
      </div>
    </Box>
  );
};

export default ChatComponent;
```
My main aim is to use methods like `getMessages()` to store and retrieve chat history from a database.

Thanks

**Comment by OvidijusParsiunas** [comment]
Hi @K-Jadeja.
If you want to apply certain properties to Deep Chat as soon as it renders, I would highly recommend using the [onComponentRender](https://deepchat.dev/docs/events#onComponentRender) event. That way you do not have to set an arbitrary timeout and can know exactly when the reference is available.

So your code would look something like this:
```
<div ref={ref}>
  <DeepChat
    onComponentRender={() => {
      if (ref.current) {
        const component = ref.current.children[0] as DeepChatCore;
        component.initialMessages = [
          {role: 'user', text: 'Hi'},
          {role: 'ai', text: 'Bye'},
        ];
      }
    }}
    request={{url: 'https://test.up.railway.app/test/stream'}}
    requestInterceptor={requestInterceptor}
    responseInterceptor={responseInterceptor}
    requestBodyLimits={{maxMessages: -1}}
    stream={true}
  />
</div>
```

Let me know if you need any further assistance.

I have thought about this a little more and will update the [onComponentRender](https://deepchat.dev/docs/events#onComponentRender) event to pass the actual component as an argument, so it would be easier to access it. I'll include it in the next release.
For now, the above example should work just fine.

**Comment by K-Jadeja** [comment]
Thanks @OvidijusParsiunas!

The code works but I still get these errors `Property 'children' does not exist on type 'never'` and `'ref.current' is possibly 'null'.`
![image](https://github.com/OvidijusParsiunas/deep-chat/assets/113630783/30bfee39-e080-4b0c-b64b-d3563e314667)

Did I miss something?

**Comment by K-Jadeja** [comment]
Thank you so much @OvidijusParsiunas! It works now :)

**Comment by OvidijusParsiunas** [comment]
Happy to hear it helped! I will close this issue. Thanks!
